<a href="https://colab.research.google.com/github/obeabi/ProjectPortfolio/blob/master/Weekly_Entry_etf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
!pip install --upgrade yfinance
!pip install  --upgrade pandas_ta
!pip install ta pandas_ta
!pip install scipy==1.16.2

WARNING: Ignoring invalid distribution ~cipy (/usr/local/lib/python3.12/dist-packages)
Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.3.3)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.6)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.5.1)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (3.18.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.5)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2025.11.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.23)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
WARNING: Ignoring invalid distribution ~cipy (/usr/local/lib/python3.12/dist-packages)
WARNING: Ignoring invalid distribution ~cipy (/usr/local/lib/python3.12/dist-packages)
Requirement already satisfied: pandas_ta in /usr/local/lib/python3.12/dist-packages (0.4.71b0)
Requirement already satisfied: numba==0.61.2 in /usr/local/lib/python3.12/dist-packages (from pandas_ta) (0.61.2)
Requirement already satisfied: numpy>=2.2.6 in /usr/local/lib/python3.12/dist-packages (from pandas_ta) (2.2.6)
Requirement already satisfied: pandas>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from pandas_ta) (2.3.3)
Requirement already satisfied: tqdm>=4.67.1 in /usr/local/lib/python3.12/dist-packages (from pandas_ta) (4.67.1)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba==0.61.2->pandas_ta) (0.44.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.3.2->pandas_ta) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.3.2->pandas_ta) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.3.2->pandas_ta) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.3.2->pandas_ta) (1.17.0)
WARNING: Ignoring invalid distribution ~cipy (/usr/local/lib/python3.12/dist-packages)
WARNING: Ignoring invalid distribution ~cipy (/usr/local/lib/python3.12/dist-packages)
Requirement already satisfied: ta in /usr/local/lib/python3.12/dist-packages (0.11.0)
Requirement already satisfied: pandas_ta in /usr/local/lib/python3.12/dist-packages (0.4.71b0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from ta) (2.2.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from ta) (2.3.3)
Requirement already satisfied: numba==0.61.2 in /usr/local/lib/python3.12/dist-packages (from pandas_ta) (0.61.2)
Requirement already satisfied: tqdm>=4.67.1 in /usr/local/lib/python3.12/dist-packages (from pandas_ta) (4.67.1)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba==0.61.2->pandas_ta) (0.44.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->ta) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->ta) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->ta) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->ta) (1.17.0)
WARNING: Ignoring invalid distribution ~cipy (/usr/local/lib/python3.12/dist-packages)
WARNING: Ignoring invalid distribution ~cipy (/usr/local/lib/python3.12/dist-packages)
Collecting scipy==1.16.2
  Using cached scipy-1.16.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (62 kB)
Requirement already satisfied: numpy<2.6,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from scipy==1.16.2) (2.2.6)
Using cached scipy-1.16.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (35.7 MB)
WARNING: Ignoring invalid distribution ~cipy (/usr/local/lib/python3.12/dist-packages)
Installing collected packages: scipy
WARNING: Ignoring invalid distribution ~cipy (/usr/local/lib/python3.12/dist-packages)
Successfully installed scipy

In [22]:
import yfinance as yf
print(yf.__version__)
import pandas as pd
import numpy as np
from datetime import datetime
import time
import ta
import requests
from datetime import datetime, timedelta
from scipy.stats import linregress
from transformers import pipeline
print("Libraries Installed!")

0.2.66
Libraries Installed!

In [23]:
today = datetime.today()
start_of_year = today.replace(month=1, day=1)

# First day of this month
first_day_month = today.replace(day=1)

# First day of this week (Monday as weekday 0)
first_day_week = today - timedelta(days=today.weekday())
print("First day of year:", start_of_year)

print("\nFirst day of this month:", first_day_month)
print("\nFirst day of this week:", first_day_week)

def most_recent_quarter_start(today=None):
    if today is None:
        today = pd.Timestamp.today().normalize()
    year = today.year
    month = today.month

    # Determine quarter start months: Jan, Apr, Jul, Oct
    if month >= 10:
        q_start = pd.Timestamp(year, 10, 1)
    elif month >= 7:
        q_start = pd.Timestamp(year, 7, 1)
    elif month >= 4:
        q_start = pd.Timestamp(year, 4, 1)
    else:
        q_start = pd.Timestamp(year, 1, 1)

    return q_start

# Example usage
print("Today:", pd.Timestamp.today().normalize())
print("Most recent quarter start:", most_recent_quarter_start())

First day of year: 2025-01-01 17:40:32.020235

First day of this month: 2025-12-01 17:40:32.020235

First day of this week: 2025-12-15 17:40:32.020235
Today: 2025-12-21 00:00:00
Most recent quarter start: 2025-10-01 00:00:00

In [24]:
# List of ETFs to analyze
#df_o = pd.read_csv('stock_list.csv')

df_raw = pd.read_csv('etf_list.csv')
df_raw = df_raw[df_raw['Type'].isin(['ETF','Stock','ASX'])]
recent_quarter = most_recent_quarter_start()
etfs = df_raw['Asset'].to_list()
print(etfs)

print(len(etfs))

['SLV', 'NFXS', 'EPU', 'GDXJ', 'GMET', 'OZEM', 'ISRA', 'ICOP', 'RING', 'GDX', 'EIS', 'IAT', 'SLX', 'PSCM', 'EWO', 'EUFN', 'HEWJ', 'IAUM', 'GLDM', 'OUNZ', 'GLD', 'IAU', 'PSCT', 'SOXX', 'SOXQ', 'REKT', 'EWP', 'SMH', 'DGRE', 'EVMT', 'EWL', 'MADE', 'PSCF', 'EIRL', 'DGIN', 'EWC', 'EWI', 'IYG', 'QQQJ', 'PVAL', 'REK', 'IXG', 'SPEU', 'EPOL', 'IDRV', 'EWM', 'IBOT', 'VCN', 'IYM', 'SPDW', 'FEZ', 'HAP', 'PSCI', 'HEZU', 'MXI', 'WTV', 'XLK', 'HAWX', 'ARTY', 'IEV', 'BLCV', 'YXI', 'VGK', 'PWB', 'DWMF', 'IEUR', 'MU', 'WDC', 'EPAM', 'TER', 'LRCX', 'CTSH', 'PLTR', 'STX', 'CRM', 'ON', 'KLAC', 'ACN', 'AMAT', 'JBL', 'ADI', 'KEYS', 'GLW', 'QCOM', 'CSCO', 'WBD', 'FOXA', 'FOX', 'TKO', 'JBHT', 'LUV', 'UAL', 'DAL', 'ODFL', 'GEV', 'UPS', 'HII', 'EXPD', 'CHRW', 'DOV', 'FDX', 'PCAR', 'GWW', 'TXT', 'CMI', 'RTX', 'PH', 'FTV', 'WAB', 'JCI', 'IEX', 'AME', 'CSX', 'GE', 'HUBB', 'KEY', 'IVZ', 'COF', 'SYF', 'AIG', 'APO', 'C', 'USB', 'JKHY', 'CFG', 'GS', 'STT', 'FITB', 'RF', 'WFC', 'PNC', 'TFC', 'MTB', 'PRU', 'AIZ', 'SCHW', 'NTRS', 'MS', 'CPAY', 'CB', 'BEN', 'AXP', 'NDAQ', 'PFG', 'EXPE', 'GM', 'CCL', 'LULU', 'ABNB', 'TPR', 'TSLA', 'ULTA', 'ROST', 'MAR', 'MGM', 'HLT', 'GGP.AX', 'IGO.AX', 'AAI.AX', 'EMR.AX', 'MIN.AX', 'SGM.AX', 'VAU.AX', 'CIA.AX', 'RIO.AX', 'NEM.AX', 'SFR.AX', 'PDN.AX', 'S32.AX', 'EVN.AX', 'ORI.AX', 'FBU.AX', 'FMG.AX', 'GMD.AX', 'BHP.AX', 'NIC.AX', 'RMS.AX']
177

## Filter for liquidity

In [25]:

# Filter ETFs or stocks for liquidity
def filter_by_liquidity(etf_df, ticker_col="Asset", min_dollar_vol=10e6, lookback_days=30):
    liquid_etfs = []

    for ticker in etf_df[ticker_col]:
        try:
            # Fetch daily historical data
            data = yf.download(ticker, period=f"{lookback_days*2}d", interval="1d", auto_adjust=True)

            if data.empty:
                continue

            # Calculate dollar volume (Close × Volume)
            data["dollar_volume"] = data["Close"] * data["Volume"]

            # Calculate rolling average over lookback_days
            avg_dollar_volume = data["dollar_volume"].rolling(window=lookback_days).mean().iloc[-1]

            # Check liquidity condition
            if avg_dollar_volume >= min_dollar_vol:
                liquid_etfs.append(ticker)

        except Exception as e:
            print(f"Error fetching {ticker}: {e}")

    # Return filtered DataFrame
    return etf_df[etf_df[ticker_col].isin(liquid_etfs)]

# Example usage
df = pd.DataFrame({"Assets": etfs})
liquid_df = filter_by_liquidity(df, ticker_col="Assets")
df_o = df_raw[df_raw['Asset'].isin(liquid_df['Assets'])]
etfs = df_o['Asset'].to_list()
print("")
print(etfs)
print(len(etfs))

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['VCN']: YFPricesMissingError('possibly delisted; no price data found  (period=60d)')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

['SLV', 'GDXJ', 'RING', 'GDX', 'IAT', 'EUFN', 'IAUM', 'GLDM', 'OUNZ', 'GLD', 'IAU', 'SOXX', 'SOXQ', 'EWP', 'SMH', 'EWL', 'EWC', 'EWI', 'IYG', 'PVAL', 'IYM', 'SPDW', 'FEZ', 'WTV', 'XLK', 'ARTY', 'IEV', 'VGK', 'IEUR', 'MU', 'WDC', 'EPAM', 'TER', 'LRCX', 'CTSH', 'PLTR', 'STX', 'CRM', 'ON', 'KLAC', 'ACN', 'AMAT', 'JBL', 'ADI', 'KEYS', 'GLW', 'QCOM', 'CSCO', 'WBD', 'FOXA', 'FOX', 'TKO', 'JBHT', 'LUV', 'UAL', 'DAL', 'ODFL', 'GEV', 'UPS', 'HII', 'EXPD', 'CHRW', 'DOV', 'FDX', 'PCAR', 'GWW', 'TXT', 'CMI', 'RTX', 'PH', 'FTV', 'WAB', 'JCI', 'IEX', 'AME', 'CSX', 'GE', 'HUBB', 'KEY', 'IVZ', 'COF', 'SYF', 'AIG', 'APO', 'C', 'USB', 'JKHY', 'CFG', 'GS', 'STT', 'FITB', 'RF', 'WFC', 'PNC', 'TFC', 'MTB', 'PRU', 'AIZ', 'SCHW', 'NTRS', 'MS', 'CPAY', 'CB', 'BEN', 'AXP', 'NDAQ', 'PFG', 'EXPE', 'GM', 'CCL', 'LULU', 'ABNB', 'TPR', 'TSLA', 'ULTA', 'ROST', 'MAR', 'MGM', 'HLT', 'GGP.AX', 'IGO.AX', 'AAI.AX', 'EMR.AX', 'MIN.AX', 'SGM.AX', 'VAU.AX', 'RIO.AX', 'NEM.AX', 'SFR.AX', 'PDN.AX', 'S32.AX', 'EVN.AX', 'ORI.AX', 'FMG.AX', 'GMD.AX', 'BHP.AX', 'RMS.AX']
137

# Classify Sector Stages

In [26]:

def weinstein_stage(df, sma_window1=10, sma_window=30,smaSlope_window=3):
    """Determine Weinstein stage using 30-week SMA and its slope."""
     # Handle MultiIndex columns
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    df["SMA"] = df["Close"].rolling(window=sma_window).mean()
    df["10_SMA"] = df["Close"].rolling(window=sma_window1).mean()

    # Compute linear regression slope on last N SMA points
    if len(df.dropna()) < sma_window:
        return None  # not enough data

    slope, _, _, _, _ = linregress(range(smaSlope_window), df["SMA"].tail(smaSlope_window))
    slope_short, _, _, _, _ = linregress(range(smaSlope_window), df["10_SMA"].tail(smaSlope_window))

    latest_price = df["Close"].iloc[-1]
    latest_sma   = df["SMA"].iloc[-1]
    latest_10sma = df["10_SMA"].iloc[-1]

    # Determine stage
    if (latest_price > latest_sma) and (slope > 0) and (slope_short > 0) and (latest_price > latest_10sma) and (latest_10sma > latest_sma):
        stage = "Stage 2 (Advancing)"
    elif latest_price < latest_sma and slope < 0:
        stage = "Stage 4 (Declining)"
    elif np.abs(slope) <= 0.001:
        stage = "Stage 1 (Basing)"
    else:
        stage = "Stage 3 (Topping)"

    return stage, slope, latest_price, latest_sma, latest_10sma,slope_short

In [27]:

results = []
for etf in etfs:
    df = yf.download(etf, period="3y", interval="1wk", auto_adjust=True)
    stage_info = weinstein_stage(df)
    if stage_info:
        stage, slope, price, sma,sma_10, sma_short = stage_info
        results.append({
            "ETF": etf,
            "Stage": stage,
            "SMA_Slope": slope,
            "Latest_Price": price,
            "30W_SMA": sma,
            "10W_SMA": sma_10,
            "10W_SMA_Slope": sma_short
        })

stages_df = pd.DataFrame(results).sort_values(by="SMA_Slope", ascending=False)
#print(len(stages_df))
stages_df.head()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

,ETF,Stage,SMA_Slope,Latest_Price,30W_SMA,10W_SMA,10W_SMA_Slope
39,KLAC,Stage 2 (Advancing),15.015073,1245.670044,1000.716115,1174.095386,17.939062
88,GS,Stage 2 (Advancing),9.705078,893.479980,744.508671,810.598596,11.738385
57,GEV,Stage 2 (Advancing),7.305001,658.280029,584.501709,603.939661,6.546994
69,PH,Stage 2 (Advancing),7.172667,874.809998,755.204266,828.859222,14.149173
114,ULTA,Stage 2 (Advancing),6.324001,597.880005,517.422669,547.356006,4.687000

In [28]:
advancing_stocks= stages_df[stages_df["Stage"] .isin(["Stage 2 (Advancing)"]) ]
advancing_stocks.reset_index(drop=True, inplace=True)
advancing_stocks.head()

,ETF,Stage,SMA_Slope,Latest_Price,30W_SMA,10W_SMA,10W_SMA_Slope
0,KLAC,Stage 2 (Advancing),15.015073,1245.670044,1000.716115,1174.095386,17.939062
1,GS,Stage 2 (Advancing),9.705078,893.479980,744.508671,810.598596,11.738385
2,GEV,Stage 2 (Advancing),7.305001,658.280029,584.501709,603.939661,6.546994
3,PH,Stage 2 (Advancing),7.172667,874.809998,755.204266,828.859222,14.149173
4,ULTA,Stage 2 (Advancing),6.324001,597.880005,517.422669,547.356006,4.687000

In [29]:
# List of ETFs to analyze
df_o = df_o[df_o['Asset'].isin(advancing_stocks['ETF'])]
#df_raw = pd.read_csv('etf_list.csv')
#df_raw = df_raw[df_raw['Type'].isin(['ETF','Stock'])]
#recent_quarter = most_recent_quarter_start()
etfs = df_o['Asset'].to_list()
print(etfs)

print(len(etfs))

['SLV', 'GDXJ', 'RING', 'GDX', 'IAT', 'EUFN', 'IAUM', 'GLDM', 'OUNZ', 'GLD', 'IAU', 'SOXX', 'SOXQ', 'EWP', 'SMH', 'EWL', 'EWC', 'EWI', 'IYG', 'PVAL', 'IYM', 'SPDW', 'FEZ', 'WTV', 'XLK', 'IEV', 'VGK', 'IEUR', 'MU', 'WDC', 'EPAM', 'TER', 'LRCX', 'CTSH', 'PLTR', 'STX', 'KLAC', 'AMAT', 'JBL', 'ADI', 'KEYS', 'GLW', 'QCOM', 'CSCO', 'WBD', 'FOXA', 'FOX', 'TKO', 'JBHT', 'LUV', 'UAL', 'DAL', 'GEV', 'UPS', 'HII', 'EXPD', 'CHRW', 'DOV', 'FDX', 'PCAR', 'TXT', 'CMI', 'RTX', 'PH', 'FTV', 'WAB', 'JCI', 'AME', 'CSX', 'GE', 'HUBB', 'KEY', 'IVZ', 'COF', 'SYF', 'C', 'USB', 'JKHY', 'CFG', 'GS', 'STT', 'FITB', 'RF', 'WFC', 'PNC', 'TFC', 'PRU', 'AIZ', 'SCHW', 'NTRS', 'MS', 'CB', 'AXP', 'PFG', 'EXPE', 'GM', 'TPR', 'TSLA', 'ULTA', 'ROST', 'MAR', 'HLT', 'IGO.AX', 'AAI.AX', 'EMR.AX', 'MIN.AX', 'SGM.AX', 'VAU.AX', 'RIO.AX', 'NEM.AX', 'SFR.AX', 'PDN.AX', 'S32.AX', 'EVN.AX', 'ORI.AX', 'FMG.AX', 'GMD.AX', 'BHP.AX', 'RMS.AX']
119

In [30]:
def macdv(prices, fast=12, slow=26, signal=9, atr_window=10, thresholds=(50, 150)):
    """
    Compute MACD-V (volatility normalized MACD).

    Parameters
    ----------
    prices : pd.Series
        Price series (e.g. closing prices).
    fast : int
        Fast EMA period.
    slow : int
        Slow EMA period.
    signal : int
        Signal EMA period for MACD line.
    atr_window : int
        ATR lookback window.
    thresholds : tuple
        (lower, upper) thresholds for neutral/ranging and extreme momentum zones.

    Returns
    -------
    pd.DataFrame with columns:
        - MACDV : MACD-V value
        - Signal : EMA of MACDV
        - Histogram : MACDV - Signal
        - EntryFlag : True when momentum is strong enough, False otherwise
    """
    # --- Step 1: EMAs for MACD ---
    ema_fast = prices.ewm(span=fast, adjust=False).mean()
    ema_slow = prices.ewm(span=slow, adjust=False).mean()
    macd_raw = ema_fast - ema_slow

    # --- Step 2: ATR for normalization ---
    high = prices.shift(1) * (1 + 0.01)   # synthetic highs/lows if OHLC not available
    low = prices.shift(1) * (1 - 0.01)
    close = prices
    tr1 = high - low
    tr2 = (high - close.shift(1)).abs()
    tr3 = (low - close.shift(1)).abs()
    tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
    atr = tr.rolling(atr_window).mean()

    # --- Step 3: Normalize MACD by ATR ---
    macdv = (macd_raw / atr) * 100

    # --- Step 4: Signal line and histogram ---
    signal_line = macdv.ewm(span=signal, adjust=False).mean()
    histogram = macdv - signal_line

    # --- Step 5: Entry conditions ---
    lower, upper = thresholds
    entry_flag = ((macdv.abs() > lower) & (macdv.abs() < upper)) | (macdv.abs() > upper)

    df = pd.DataFrame({
        "MACDV": macdv,
        "Signal": signal_line,
        "Histogram": histogram,
        "EntryFlag": entry_flag
    })
    curr = df.iloc[-1]

    return curr.EntryFlag

def money_flow_signals(df, period=10):
    """
    Calculate Money Flow Index (MFI) and generate signals:
    - Positive money flow (TP > TP_prev)
    - Divergence (Price vs MFI mismatch)

    Parameters:
        df (pd.DataFrame): DataFrame with columns ["High", "Low", "Close", "Volume"]
        period (int): Lookback period for MFI (default=10)

    Returns:
        pd.DataFrame with added columns: ["TypicalPrice", "MFI", "PositiveFlow", "Divergence"]
    """

    df = df.copy()

    # Step 1: Typical Price
    df["TypicalPrice"] = (df["High"] + df["Low"] + df["Close"]) / 3

    # Step 2: Raw Money Flow
    df["RawMoneyFlow"] = df["TypicalPrice"] * df["Volume"]

    # Step 3: Positive & Negative Flow
    df["PositiveFlow"] = np.where(df["TypicalPrice"] > df["TypicalPrice"].shift(1), df["RawMoneyFlow"], 0.0)
    df["NegativeFlow"] = np.where(df["TypicalPrice"] < df["TypicalPrice"].shift(1), df["RawMoneyFlow"], 0.0)

    # Step 4: Money Flow Ratio & MFI
    pos_flow = df["PositiveFlow"].rolling(period).sum()
    neg_flow = df["NegativeFlow"].rolling(period).sum()
    money_flow_ratio = pos_flow / neg_flow.replace(0, np.nan)
    df["MFI"] = 100 - (100 / (1 + money_flow_ratio))

    # Step 5: Positive Money Flow Signal
    df["PositiveFlowSignal"] = df["TypicalPrice"] > df["TypicalPrice"].shift(1)

    # Step 6: Divergence Detection
    df["PriceHigh"] = df["Close"].rolling(period).max()
    df["PriceLow"] = df["Close"].rolling(period).min()
    df["MFIHigh"] = df["MFI"].rolling(period).max()
    df["MFILow"] = df["MFI"].rolling(period).min()

    def divergence(row):
        if np.isnan(row["MFI"]):
            return None
        # Price makes higher high, but MFI does not
        if row["Close"] >= row["PriceHigh"] and row["MFI"] < row["MFIHigh"]:
            return "Bearish Divergence ⚠️"
        # Price makes lower low, but MFI does not
        elif row["Close"] <= row["PriceLow"] and row["MFI"] > row["MFILow"]:
            return "Bullish Divergence ✅"
        else:
            return "No Divergence"

    df["Divergence"] = df.apply(divergence, axis=1)
    df['Entry_signal']= (df["MFI"] > 50) & (df["Divergence"] == "No Divergence")
    curr = df.iloc[-1]

    return curr.Entry_signal

In [31]:
# Function to fetch historical weekly data


def anchored_vwap(ticker: str, lookback_weeks: int = 5):
    """
    Calculate the Anchored VWAP from the most recent high within the past `lookback_weeks`
    and create a 'Signal' column that gives 'Buy' when Close > Anchored_VWAP, else 'No-Buy'.

    Args:
        ticker (str): Stock ticker symbol
        lookback_weeks (int): Number of weeks to look back for the highest price

    Returns:
        pandas.DataFrame: DataFrame with OHLC, Volume, Anchored_VWAP, and Signal columns
    """
    try:
        # --- Fetch 6 months of daily data to cover the lookback window
        data = yf.download(ticker, period="6mo", interval="1d", progress=False,auto_adjust=True)
        if isinstance(data.columns, pd.MultiIndex):
          data.columns = data.columns.get_level_values(0)  # keep only first level

        if data.empty:
            raise ValueError(f"No data retrieved for ticker {ticker}")

        data.dropna(inplace=True)
        data.index = pd.to_datetime(data.index)

        # --- Ensure we have enough data for the lookback period
        min_days_required = lookback_weeks * 10  # ~5 trading days per week
        if len(data) < min_days_required:
            raise ValueError(f"Insufficient data: {len(data)} days available, {min_days_required} required")

        # --- Find the most recent high within the past lookback_weeks
        recent_period = data.tail(min_days_required)
        anchor_date = recent_period['High'].idxmax()

        # --- Verify anchor_date is a valid Timestamp
        if not isinstance(anchor_date, pd.Timestamp):
            raise ValueError(f"Invalid anchor_date: {anchor_date}. Expected a Timestamp.")

        anchor_price = recent_period.loc[anchor_date, 'High']

        # --- Use .date() safely since we confirmed anchor_date is a Timestamp
        print(f"\nAnchored VWAP for {ticker} starting from {anchor_date.date()} (recent high = {anchor_price:.2f})")

        # --- Slice data from the anchor date onwards
        anchor_data = data.loc[anchor_date:]

        # --- Compute VWAP starting from the anchor date
        # Use typical price ((H+L+C)/3) for more accurate VWAP
        typical_price = (anchor_data['High'] + anchor_data['Low'] + anchor_data['Close']) / 3
        q = anchor_data['Volume']
        pv = (typical_price * q).cumsum()
        v = q.cumsum()

        # --- Avoid division by zero
        avwap = pv / v.where(v != 0, np.nan)

        # --- Add Anchored VWAP to the full dataset
        data['Anchored_VWAP'] = np.nan  # Initialize with NaN
        data.loc[anchor_date:, 'Anchored_VWAP'] = avwap
        # --- Add swing high information to the DataFrame
        data['Swing_High_Price'] = anchor_price
        data['Swing_High_Date'] = anchor_date

        # --- Create Buy/No-Buy Signal
        # Only apply signal where Anchored_VWAP is not NaN
        data['Signal'] = np.where(
            (data['Close'] > data['Anchored_VWAP']) & (data['Anchored_VWAP'].notna()),
            True,
            False
        )

        return data[['Anchored_VWAP', 'Signal','Swing_High_Price']]

    except Exception as e:
        print(f"Error processing {ticker}: {str(e)}")
        return None


def anchored_vwap_old(ticker, anchor_date):
    """
    Calculate Anchored VWAP starting from a given anchor_date.
    Works with both single-level and multi-level columns (e.g. yfinance output).
    """
    # --- Step 1: Flatten columns if multi-index ---
    df = yf.download(ticker, period="1y", interval="1d",auto_adjust=True)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)  # keep only first level

    # --- Step 2: Ensure required columns exist ---
    required_cols = ["High", "Low", "Close", "Volume"]
    for col in required_cols:
        if col not in df.columns:
            raise ValueError(f"Missing required column: {col}")

    # --- Step 3: Subset from anchor_date ---
    df_anchor = df.loc[df.index >= pd.to_datetime(anchor_date)].copy()
    if df_anchor.empty:
        raise ValueError(f"No data found on/after {anchor_date}")

    # --- Step 4: Compute typical price ---
    df_anchor["typical_price"] = (df_anchor["High"] + df_anchor["Low"] + df_anchor["Close"]) / 3.0

    # --- Step 5: Cumulative PV and VWAP ---
    df_anchor["cum_pv"] = (df_anchor["typical_price"].astype(float) * df_anchor["Volume"].astype(float)).cumsum()
    df_anchor["cum_vol"] = df_anchor["Volume"].astype(float).cumsum()
    df_anchor["anchored_vwap"] = df_anchor["cum_pv"] / df_anchor["cum_vol"]

    return df_anchor[["anchored_vwap"]]

def get_monthly_data(ticker):
  try:
      df = yf.download(ticker, period="10y", interval="1mo",auto_adjust=True)

      #if isinstance(df.columns, pd.MultiIndex):
        #df.columns = df.columns.get_level_values(0)  # keep only first level
      # Compute MACD using ta
      df['10_month_SMA'] = df['Close'].rolling(window=10).mean()
      slope, _, _, _, _ = linregress(range(3), df["10_month_SMA"].tail(3))
      df['SMA_Slope'] = slope
      # Calculate MACD and Signal Line
      df['12_EMA'] = df['Close'].ewm(span=12, adjust=False).mean()
      df['26_EMA'] = df['Close'].ewm(span=26, adjust=False).mean()
      # Compute MACD Line
      df['MACD_Line'] = df['12_EMA'] - df['26_EMA']
      # Compute Signal Line (9-day EMA of MACD Line)
      df['Signal_Line'] = df['MACD_Line'].ewm(span=9, adjust=False).mean()
      df['MACD_Hist'] = df['MACD_Line'] - df['Signal_Line']
      #df['AvgVolume'] = df["Volume"].rolling(window=10).mean()
      df['RVOL'] = df['Volume'] / df['Volume'].rolling(window=10).mean()
      df['RVOL_Slope'] = df['RVOL'].diff()
      # Calculate ADX, +DMI and -DMI
      high = df['High']
      low = df['Low']
      close = df['Close']
      # Calculate directional movements
      up_move = high.diff()
      down_move = -low.diff()
      plus_dm = np.where((up_move > down_move) & (up_move > 0), up_move, 0.0)
      minus_dm = np.where((down_move > up_move) & (down_move > 0), down_move, 0.0)
      # Calculate True Range (TR)
      tr1 = high - low
      tr2 = (high - close.shift()).abs()
      tr3 = (low - close.shift()).abs()
      tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
      # Smooth TR, +DM, and -DM using Wilder’s smoothing
      atr = tr.rolling(window=14).sum()
      plus_dm_series = pd.Series(plus_dm.ravel(), index=df.index).astype(float)
      minus_dm_series = pd.Series(minus_dm.ravel(), index=df.index).astype(float)
      plus_dm_smoothed = plus_dm_series.rolling(window=14).sum()
      minus_dm_smoothed = minus_dm_series.rolling(window=14).sum()
      # Directional Indicators
      plus_di = 100 * (plus_dm_smoothed / atr)
      minus_di = 100 * (minus_dm_smoothed / atr)
      # DX and ADX
      dx = 100 * (np.abs(plus_di - minus_di) / (plus_di + minus_di))
      adx = dx.rolling(window=14).mean()
      # Add results to original DataFrame
      df['+DI'] = plus_di
      df['-DI'] = minus_di
      df['ADX'] = adx
      df['di_flag'] = df['+DI'] > df['-DI']
      df['di_flag'] = df['di_flag'].astype(int)
      df['adx_indicator'] = np.where(df['ADX'] > 14, 1, 0)
      df['adx_signal'] = df['adx_indicator'] * df['di_flag']

      return df
  except Exception as e:
      print("There is an error getting monthly data", e)

def get_weekly_data(ticker):
  try:
      df = yf.download(ticker, period="10y", interval="1wk",auto_adjust=True)
      #if isinstance(df.columns, pd.MultiIndex):
        #df.columns = df.columns.get_level_values(0)  # keep only first level
      df['10_week_SMA'] = df['Close'].rolling(window=10).mean()
      df['30_week_SMA'] = df['Close'].rolling(window=30).mean()
      slope, _, _, _, _ = linregress(range(5), df["10_week_SMA"].tail(5))
      df['SMA_Slope'] = slope
      df['10_EMA'] = df['Close'].ewm(span=10, adjust=False).mean()
      df['20_EMA'] = df['Close'].ewm(span=20, adjust=False).mean()
      df['ATR'] = compute_atr(df, 14)
      df['OBV'] = compute_obv(df)
      obv_slope, _, _, _, _ = linregress(range(30), df["OBV"].tail(30))
      df['OBV_Slope'] = obv_slope
      df['30_week_avg_volume'] = df['Volume'].rolling(window=30).mean()
      # Calculate MACD and Signal Line
      df['12_EMA'] = df['Close'].ewm(span=12, adjust=False).mean()
      df['21_EMA'] = df['Close'].ewm(span=21, adjust=False).mean()
      df['26_EMA'] = df['Close'].ewm(span=26, adjust=False).mean()
      # Compute MACD Line
      df['MACD_Line'] = df['12_EMA'] - df['26_EMA']
      # Compute Signal Line (9-day EMA of MACD Line)
      df['Signal_Line'] = df['MACD_Line'].ewm(span=9, adjust=False).mean()
      df['MACD_Hist'] = df['MACD_Line'] - df['Signal_Line']
      # Compute raw EFI
      df['EFI'] = (df['Close'].diff()) * df['Volume']
      # Compute EMA of EFI
      df['EFI_EMA'] = df['EFI'].ewm(span=13, adjust=False).mean()
      # Determine if EFI_EMA is rising or falling
      df['EFI_EMA_Trend'] = df['EFI_EMA'].diff().apply(lambda x: 'Rising' if x > 0 else 'Falling')
      # Calculate ADX, +DMI and -DMI
      high = df['High']
      low = df['Low']
      close = df['Close']
      # Calculate directional movements
      up_move = high.diff()
      down_move = -low.diff()
      plus_dm = np.where((up_move > down_move) & (up_move > 0), up_move, 0.0)
      minus_dm = np.where((down_move > up_move) & (down_move > 0), down_move, 0.0)
      # Calculate True Range (TR)
      tr1 = high - low
      tr2 = (high - close.shift()).abs()
      tr3 = (low - close.shift()).abs()
      tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
      # Smooth TR, +DM, and -DM using Wilder’s smoothing
      atr = tr.rolling(window=14).sum()
      plus_dm_series = pd.Series(plus_dm.ravel(), index=df.index).astype(float)
      minus_dm_series = pd.Series(minus_dm.ravel(), index=df.index).astype(float)
      plus_dm_smoothed = plus_dm_series.rolling(window=14).sum()
      minus_dm_smoothed = minus_dm_series.rolling(window=14).sum()
      # Directional Indicators
      plus_di = 100 * (plus_dm_smoothed / atr)
      minus_di = 100 * (minus_dm_smoothed / atr)
      # DX and ADX
      dx = 100 * (np.abs(plus_di - minus_di) / (plus_di + minus_di))
      adx = dx.rolling(window=14).mean()
      # Add results to original DataFrame
      df['+DI'] = plus_di
      df['-DI'] = minus_di
      df['ADX'] = adx
      df['di_flag'] = df['+DI'] > df['-DI']
      df['di_flag'] = df['di_flag'].astype(int)
      df['adx_indicator'] = np.where(df['ADX'] > 14, 1, 0)
      df['adx_signal'] = df['adx_indicator'] * df['di_flag']

      # --- Overhead Resistance Filter ---
      recent_52_weeks = df[-52:]
      max_close_52w = recent_52_weeks['Close'].max().iloc[0]
      max_price = df['Close'].max().iloc[0]
      last_close = df['Close'].iloc[-1].iloc[0]
      # Filter condition: Close is within 15% of 52-week high
      df['No_Overhead_Resistance'] = last_close > (max_close_52w*0.80)
      # --- Above 52 weeks High ---
      df['above_52w_high'] = last_close > max_close_52w
      df['below_52w_high'] = last_close < max_close_52w

      return df
  except Exception as e:
      print("There is an error getting weekly data", e)

def is_macd_bullish(df):
    """
    Determines if there is a bullish signal on the MACD indicator.
    A bullish signal occurs when the MACD line is above the signal line.

    Parameters:
    - df: dataframe. Must have columns 'MACD_Line' and 'Signal_Line'.
    Returns:
    - bool: True if a bullish signal is detected, otherwise False.
    """
    try:
      if df.empty:
        return False
      # Calculate MACD histogram if not already present

      curr = df.iloc[-3:]
      macd_crossover = curr['MACD_Line'].iloc[-1] > curr['Signal_Line'].iloc[-1]
      hist_increasing = (curr['MACD_Hist'].iloc[-1] > curr['MACD_Hist'].iloc[-2]) \
                         or (curr['MACD_Hist'].iloc[-2] > curr['MACD_Hist'].iloc[-3])

      return macd_crossover
              #and (hist_increasing or curr['MACD_Hist'].iloc[-1] > 0)
    except Exception as e:
      print("Something went wrong while computing the MACD", e)

def is_macd_bullish_hr(df):
    """
    Determines if there is a bullish signal on the MACD indicator on hourly chart.
    A bullish signal occurs when the MACD line is above the signal line.

    Parameters:
    - df: dataframe. Must have columns 'MACD_Line' and 'Signal_Line'.
    Returns:
    - bool: True if a bullish signal is detected, otherwise False.
    """
    try:
      if df.empty:
        return False
      # Calculate MACD histogram if not already present

      curr = df.iloc[-3:]
      macd_crossover = curr['MACD_Line'].iloc[-1] > curr['Signal_Line'].iloc[-1]

      return macd_crossover
             # and curr['MACD_Hist'].iloc[-1] > 0
    except Exception as e:
      print("Something went wrong while computing the MACD", e)

def is_macd_bullish_min(df):
    """
    Determines if there is a bullish signal on the MACD indicator on 15 minute chart.
    A bullish signal occurs when the MACD line is above the signal line.

    Parameters:
    - df: dataframe. Must have columns 'MACD_Line' and 'Signal_Line'.
    Returns:
    - bool: True if a bullish signal is detected, otherwise False.
    """
    try:
      if df.empty:
        return False
      # Calculate MACD histogram if not already present

      curr = df.iloc[-3:]
      macd_crossover = curr['MACD_Line'].iloc[-1] > curr['Signal_Line'].iloc[-1]

      return macd_crossover
    except Exception as e:
      print("Something went wrong while computing the MACD", e)

def calculate_bbw(df, window=20):
    """ Calculates Bollinger Bands Width"""
    sma = df['Close'].rolling(window).mean()
    std = df['Close'].rolling(window).std()
    upper = sma + 2*std
    lower = sma - 2*std
    bbw = (upper - lower) / sma
    return bbw

def calculate_vwap(df):
  """ Calculates vwap"""
  try:
    Typical_Price = (df['Close'].values + df['High'].values + df['Low'].values) / 3
    TPV = Typical_Price * df['Volume'].values
    vwap = TPV.cumsum() / df['Volume'].values.cumsum()
    return vwap
  except Exception as e:
    print("Something went wrong while computing the VWAP:", e)
    return None

# Function to compute RSI
def compute_rsi(series, period=10):
  try:
    delta = series.diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
    rs = gain / loss
    return 100 - (100 / (1 + rs))
  except Exception as e:
        print("Something went wrong while computing the RSI:", e)
        return None

def calculate_ma(data, length=10, ma_type="WMA"):
    if ma_type == "SMA":
        return data.rolling(window=length).mean()
    elif ma_type == "EMA":
        return data.ewm(span=length, adjust=False).mean()
    elif ma_type == "WMA":
        weights = np.arange(1, length+1)
        return data.rolling(length).apply(lambda x: np.dot(x, weights)/weights.sum(), raw=True)
    elif ma_type == "VWMA":
        return ta.volume_weighted_average_price(data, length)

def calculate_bollinger_bands(data, length=10, std_dev=2.0):
    sma = data.rolling(window=length).mean()
    std_dev = data.rolling(window=length).std()
    upper_band = sma + (std_dev * std_dev)
    lower_band = sma - (std_dev * std_dev)
    return upper_band, lower_band

# Function to compute ATR (Average True Range)
def compute_atr(df, period=10):
  try:
    df['High-Low'] = df['High'] - df['Low']
    df['High-Close'] = abs(df['High'] - df['Close'].shift(1))
    df['Low-Close'] = abs(df['Low'] - df['Close'].shift(1))
    df['TR'] = df[['High-Low', 'High-Close', 'Low-Close']].max(axis=1)
    return df['TR'].rolling(window=period).mean()
  except Exception as e:
      print("Something went wrong whilecomputing the ATR", e)


# Function to compute On-Balance Volume (OBV)
def compute_obv(df):
  try:
    # Calculate daily price change: 1 if price is up, -1 if down, 0 if unchanged
    price_change = df['Close'].diff()

    # Use price change to decide whether to add or subtract volume
    obv = (price_change > 0).astype(int) * df['Volume']  # Volume when price goes up
    obv -= (price_change < 0).astype(int) * df['Volume']  # Volume when price goes down

    # We accumulate the OBV by taking the cumulative sum of the volume changes
    obv = obv.cumsum()

    return obv
  except Exception as e:
      print("Something went wrong while computing the OBV", e)

def is_bullish_engulfing(df):
    prev = df.iloc[-2]
    curr = df.iloc[-1]
    return (
        prev['Close'].iloc[0] < prev['Open'].iloc[0] and # Previous red
        curr['Close'].iloc[0] > curr['Open'].iloc[0] and # Current green
        curr['Close'].iloc[0] > prev['Open'].iloc[0] and
        curr['Open'].iloc[0] < prev['Close'].iloc[0]
    )

# Function to calculate risk-reward ratio
def calculate_risk_reward(df):
  try:
    if df.empty or len(df) < 20:  # Ensure there are enough data points
        return np.nan

    #latest_price = df['Close'].iloc[-1].iloc[0]
    latest_price = df['Close'].iloc[-1]

    # Use the ATR for setting support level
    atr = df['ATR'].iloc[-1]  # Latest ATR value
    price_ema = df['8_day_EMA'].iloc[-1]
    atr_multiple = 1  # You can adjust this multiplier based on your strategy

    # Calculate the support level using the ATR
    trailing = atr * atr_multiple
    support_level = price_ema - trailing
    resistance_level = price_ema + 1.5*trailing

    return support_level, latest_price, trailing,resistance_level
  except Exception as e:
      print("Something went wrong while computing the reward-risk ratio", e)

# Function to fetch daily data
def get_daily_data(ticker):
    df = yf.download(ticker, period="1y", interval="1d",auto_adjust=True)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)  # keep only first level
    df['20_day_SMA'] = df['Close'].rolling(window=20).mean()
    df['20_day_EMA'] = df['Close'].ewm(span=20, adjust=False).mean()
    df['50_day_avg_volume'] = df['Volume'].rolling(window=50).mean()
    df['8_day_EMA'] = df['Close'].ewm(span=8, adjust=False).mean()
    df['15_day_EMA'] = df['Close'].ewm(span=15, adjust=False).mean()
    df['21_day_EMA'] = df['Close'].ewm(span=21, adjust=False).mean()
    df['26_day_EMA'] = df['Close'].ewm(span=26, adjust=False).mean()
    df['50_day_SMA'] = df['Close'].rolling(window=50).mean()
    df['100_day_SMA'] = df['Close'].rolling(window=100).mean()
    df['200_day_SMA'] = df['Close'].rolling(window=200).mean()
    slope_50sma, _, _, _, _ = linregress(range(5), df["50_day_SMA"].tail(5))
    df['SMA_Slope_50'] = slope_50sma
    df['ATR'] = compute_atr(df, 10)
    df["8EMA_plus_ATR"] = df["8_day_EMA"] + 1* df["ATR"]
    df["8EMA_plus_ATRL"] = df["8_day_EMA"] + 1.5* df["ATR"]
    # Compute MACD using ta
    df["MACD_Line"] = ta.trend.macd(df["Close"], window_slow=26, window_fast=12)
    df["Signal_Line"] = ta.trend.macd_signal(df["Close"], window_slow=26, window_fast=12, window_sign=9)
    df["MACD_Hist"] = ta.trend.macd_diff(df["Close"], window_slow=26, window_fast=12, window_sign=9)
    df["MACD_Hist_above_zero"] = df["MACD_Hist"] > 0
    df["MACD_Hist_below_zero"] = df["MACD_Hist"] < 0
    df['macd_above_signal'] = df['MACD_Line'] > df['Signal_Line']
    df['macd_below_signal'] = df['MACD_Line'] < df['Signal_Line']
    df['VWAP'] = calculate_vwap(df)
    # Compute raw EFI
    df['EFI'] = (df['Close'].diff()) * df['Volume']
    # Compute EMA of EFI
    df['EFI_EMA'] = df['EFI'].ewm(span=13, adjust=False).mean()
    # Determine if EFI_EMA is rising or falling
    df['EFI_EMA_Trend'] = df['EFI_EMA'].diff().apply(lambda x: 'Rising' if x > 0 else 'Falling')
    # Calculate ADX, +DMI and -DMI
    high = df['High']
    low = df['Low']
    close = df['Close']
    # Calculate directional movements
    up_move = high.diff()
    down_move = -low.diff()
    plus_dm = np.where((up_move > down_move) & (up_move > 0), up_move, 0.0)
    minus_dm = np.where((down_move > up_move) & (down_move > 0), down_move, 0.0)
    # Calculate True Range (TR)
    tr1 = high - low
    tr2 = (high - close.shift()).abs()
    tr3 = (low - close.shift()).abs()
    tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
    # Smooth TR, +DM, and -DM using Wilder’s smoothing
    atr = tr.rolling(window=14).sum()
    plus_dm_series = pd.Series(plus_dm.ravel(), index=df.index).astype(float)
    minus_dm_series = pd.Series(minus_dm.ravel(), index=df.index).astype(float)
    plus_dm_smoothed = plus_dm_series.rolling(window=14).sum()
    minus_dm_smoothed = minus_dm_series.rolling(window=14).sum()
    # Directional Indicators
    plus_di = 100 * (plus_dm_smoothed / atr)
    minus_di = 100 * (minus_dm_smoothed / atr)
    # DX and ADX
    dx = 100 * (np.abs(plus_di - minus_di) / (plus_di + minus_di))
    adx = dx.rolling(window=14).mean()
    # Add results to original DataFrame
    df['+DI'] = plus_di
    df['-DI'] = minus_di
    df['ADX'] = adx
    df['di_flag'] = df['+DI'] > df['-DI']
    df['di_flag'] = df['di_flag'].astype(int)
    df['adx_indicator'] = np.where(df['ADX'] > 14, 1, 0)
    df['adx_signal'] = df['adx_indicator'] * df['di_flag']

    return df

# Function to fetch hourly data
def get_30min_data(ticker):
    df = yf.download(ticker, interval='30m', period='60d',auto_adjust=True)
    if isinstance(df.columns, pd.MultiIndex):
      df.columns = df.columns.get_level_values(0)  # keep only first level

    df['5d_SMA'] = df['Close'].rolling(window=65).mean() # changed from 104
    slope_sma, _, _, _, _ = linregress(range(5), df["5d_SMA"].tail(5))
    df['SMA_Slope']       = slope_sma
    # Short-term & medium-term moving averages
    df['21_EMA'] = df['Close'].ewm(span=21, adjust=False).mean()
    df['50_EMA'] = df['Close'].ewm(span=50, adjust=False).mean()
    df['200_EMA'] = df['Close'].ewm(span=200, adjust=False).mean()


    # Calculate MACD and Signal Line
    df['12_EMA'] = df['Close'].ewm(span=12, adjust=False).mean()
    df['26_EMA'] = df['Close'].ewm(span=26, adjust=False).mean()
    # Compute MACD Line
    df['MACD_Line'] = df['12_EMA'] - df['26_EMA']
    # Compute Signal Line (9-day EMA of MACD Line)
    df['Signal_Line'] = df['MACD_Line'].ewm(span=9, adjust=False).mean()
    df['MACD_Hist'] = df['MACD_Line'] - df['Signal_Line']
    return df


# Function to fetch hourly data
def get_15min_data(ticker):
    df = yf.download(ticker, interval='15m', period='30d',auto_adjust=True)
    if isinstance(df.columns, pd.MultiIndex):
      df.columns = df.columns.get_level_values(0)  # keep only first level

    df['5d_SMA'] = df['Close'].rolling(window=130).mean()
    slope_sma, _, _, _, _ = linregress(range(5), df["5d_SMA"].tail(5))
    df['SMA_Slope']       = slope_sma
    # Short-term & medium-term moving averages
    df['21_EMA'] = df['Close'].ewm(span=21, adjust=False).mean()
    df['50_EMA'] = df['Close'].ewm(span=50, adjust=False).mean()
    df['200_EMA'] = df['Close'].ewm(span=200, adjust=False).mean()
    return df


# Function to check monthly trend
def is_monthly_trend_bullish(df):
    if df.empty:
        return False

    sma_slope           = df['SMA_Slope'].iloc[-1]> 0
    adx_ok              = df['adx_signal'].iloc[-1] == 1
    latest_price        = df['Close'].iloc[-1].iloc[0]
    latest_sma          = df['10_month_SMA'].iloc[-1]
    macd_bullish_signal = is_macd_bullish(df)
    above_10_month_SMA  = (latest_price > latest_sma) and sma_slope

    return above_10_month_SMA and macd_bullish_signal and adx_ok


# Function to check weekly trend
def is_weekly_trend_bullish(df):
    if df.empty:
        return False

    latest_price = df['Close'].iloc[-1].iloc[0]
    latest_30sma = df['30_week_SMA'].iloc[-1]
    latest_10sma = df['10_week_SMA'].iloc[-1]
    sma_10_above_30 = latest_10sma > latest_30sma
    above_10_week_SMA = latest_price > latest_10sma
    above_30_week_SMA = latest_price > latest_30sma
    sma_slope = df['SMA_Slope'].iloc[-1]> 0
    obv_slope = df['OBV_Slope'].iloc[-1]> 0
    macd_bullish_signal =  is_macd_bullish(df)
    elderforce_trend_ok = df['EFI_EMA_Trend'].iloc[-1] == 'Rising'
    adx_ok = df['adx_signal'].iloc[-1] == 1
    elderforce_ema_ok = df['EFI_EMA'].iloc[-1] > 0
    volume_ok = df['Volume'].iloc[-1] > df['30_week_avg_volume'].iloc[-1] # Institutional interest
    volume_ok = volume_ok.iloc[0]
    # Calculate the OBV Moving Average
    df['OBV_EMA'] = df['OBV'].ewm(span=10, adjust=False).mean()
    # OBV trending up if current OBV is above the 30-period EMA
    obv_trending_up = df['OBV'].iloc[-1] > df['OBV_EMA'].iloc[-1]
    # OBV trending down if current OBV is below the 30-period EMA
    obv_trending_down = df['OBV'].iloc[-1] < df['OBV_EMA'].iloc[-1]
    trend_ok = sma_10_above_30  and above_10_week_SMA and above_30_week_SMA and adx_ok
    no_overhead_supply = df['No_Overhead_Resistance'].iloc[-1]
    above_52w_high = df['above_52w_high'].iloc[-1]
    time.sleep(2)  # Add a delay of 1 second between requests

    return  trend_ok and macd_bullish_signal and sma_slope



# Function to check daily entry signal
def is_daily_entry_signal(df2):
    if df2.empty:
        return False

    df = df2.copy()
    latest_price = df['Close'].iloc[-1]
    sma_slope_50 = df['SMA_Slope_50'].iloc[-1]> 0
    latest_8ema = df['8_day_EMA'].iloc[-1]
    latest_15ema = df['15_day_EMA'].iloc[-1]
    latest_20sma = df['20_day_SMA'].iloc[-1]
    latest_50sma = df['50_day_SMA'].iloc[-1]
    latest_100sma = df['100_day_SMA'].iloc[-1]
    latest_200sma = df['200_day_SMA'].iloc[-1]
    above_20sma = latest_price > latest_20sma
    above_50sma = latest_price > latest_50sma
    above_100sma = latest_price > latest_100sma
    above_200sma = latest_price > latest_200sma
    above_8ema = latest_price > latest_8ema
    is_8ema_above_15ema = latest_8ema > latest_15ema
    is_20sma_above_50sma = latest_20sma > latest_50sma
    is_50sma_above_100sma = latest_50sma > latest_100sma
    is_50sma_above_200sma = latest_50sma > latest_200sma
    is_100sma_above_200sma = latest_100sma > latest_200sma
    volume_ok = df['Volume'].iloc[-1] > 1* df['50_day_avg_volume'].iloc[-1] # Institutional interest
    volume_ok = volume_ok
    macd_bullish_signal = df["MACD_Hist_above_zero"].iloc[-1] #is_macd_bullish(df)
    #vwap_price = df['VWAP'].iloc[-1]
    elderforce_trend_ok = df['EFI_EMA_Trend'].iloc[-1] == 'Rising'
    elderforce_ema_ok = df['EFI_EMA'].iloc[-1] > 0
    adx_ok = df['adx_signal'].iloc[-1] == 1
    slopes_ok =  sma_slope_50
    moving_averages_ok = above_50sma and above_100sma and above_200sma \
                          and is_50sma_above_100sma \
                          and is_50sma_above_200sma and is_100sma_above_200sma \
                          and is_8ema_above_15ema and above_8ema


    # Look for a breakout above 20-day SMA & RSI > 50
    return moving_averages_ok and adx_ok and slopes_ok


def get_heikin_ashi_signal(ticker="AAPL", period="6mo", interval="1d"):
    # Fetch OHLC data
    df = yf.download(ticker, period=period, interval=interval, auto_adjust=True)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)  # keep only first level

    # Compute Heikin Ashi candles
    ha_df = pd.DataFrame(index=df.index)
    ha_df['HA_Close'] = (df['Open'] + df['High'] + df['Low'] + df['Close']) / 4

    ha_open = []
    for i in range(len(df)):
        if i == 0:
             ha_open.append((df['Open'].iloc[i] + df['Close'].iloc[i]) / 2)
        else:
            ha_open.append((ha_open[i-1] + ha_df['HA_Close'].iloc[i-1]) / 2)
    ha_df['HA_Open'] = ha_open
    ha_df['HA_High'] = ha_df[['HA_Open', 'HA_Close']].assign(High=df['High']).max(axis=1)
    ha_df['HA_Low'] = ha_df[['HA_Open', 'HA_Close']].assign(Low=df['Low']).min(axis=1)

    # Combine with original
    df = df.join(ha_df)
    # Check for green candle with flat bottom
    last = df.iloc[-1]
    green_candle = last['HA_Close'] > last['HA_Open']
    flat_bottom = abs(last['HA_Open'] - last['HA_Low']) < 0.01  # tiny wick or flat bottom tolerance
    signal = green_candle and flat_bottom

    print(f"\n🔍 Checking {ticker} ({interval} timeframe)")
    print(f"HA_Open: {last['HA_Open']:.2f}, HA_Close: {last['HA_Close']:.2f}, HA_Low: {last['HA_Low']:.2f}")
    if signal:
        print("✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!")
    elif green_candle:
        print("🟢 Candle is green but not flat-bottomed — still bullish, but less strong.")
    else:
        print("🔴 Not a bullish candle — no entry confirmation yet.")

    return signal, green_candle

# Check entry conditions
def check_entry_conditions(tickers):
    results = []
    for ticker in tickers:
      df = get_daily_data(ticker)
      latest_price = df['Close'].iloc[-1]
      prev_price = df['Close'].iloc[-2]
      latest_sma = df['50_day_SMA'].iloc[-1]
      latest_price_8ema =df['8_day_EMA'].iloc[-1]
      latest_price_21ema =df['21_day_EMA'].iloc[-1]
      price_threshold_ATR = df['8EMA_plus_ATR'].iloc[-1]
      above_price_threshold_ATR = latest_price > price_threshold_ATR
      below_price_threshold_ATR = latest_price <= price_threshold_ATR
      macd_bullish_signal = df['macd_above_signal'].iloc[-1]
      mfi_signal = money_flow_signals(df)
      # Print results
      print(f"\nMoney flow indicator for {ticker} is:")
      print(mfi_signal)
      macdv_signal = macdv(df['Close'])
      print(f"\nMacd-V indicator for {ticker} is:")
      print(macdv_signal )


      df_entry              = get_30min_data(ticker)
      latest_priceh_5sma    = df_entry['5d_SMA'].iloc[-1]
      latest_priceh         = df_entry['Close'].iloc[-1]
      sma_slope_h           = df_entry['SMA_Slope'].iloc[-1]> 0
      HA_buy_signal_h,gc_h  = get_heikin_ashi_signal(ticker, period="90d", interval="1d")

      df_refined_entry      = get_15min_data(ticker)
      latest_pricem_5sma    = df_refined_entry['5d_SMA'].iloc[-1]
      latest_pricem         = df_refined_entry['Close'].iloc[-1]
      sma_slope_m           = df_refined_entry['SMA_Slope'].iloc[-1]> 0
      #HA_buy_signal_m,gc_m = get_heikin_ashi_signal(ticker, period="30d", interval="15m")



      refined_entry_signal = (HA_buy_signal_h or gc_h or macdv_signal or mfi_signal ) \
                              and ((latest_priceh >  latest_priceh_5sma) or sma_slope_h) \
                              and ((latest_pricem >  latest_pricem_5sma) or sma_slope_m)


      if latest_price >= latest_price_8ema and above_price_threshold_ATR :
        entry_signal = "Extended Momentum Entry"
      elif latest_price >= latest_price_8ema and below_price_threshold_ATR and refined_entry_signal  :
        entry_signal = "Aline Entry"
      elif (latest_price < latest_price_8ema) and (latest_price >= latest_price_21ema) :
          entry_signal= "Bline Entry"
      elif  (latest_price <= latest_price_21ema) and (latest_price >= latest_sma) :
          entry_signal = "Below Bline Entry"
      elif  latest_price < latest_sma:
          entry_signal = "Bearish"

      else:
        entry_signal = "Other"
      results.append([ticker, entry_signal])
    # Convert results to DataFrame
    df_results = pd.DataFrame(results, columns=["Asset", "Entry_Signal"])
    return df_results

# Multi-timeframe strategy check returning a DataFrame
def check_mtf_entry(tickers):
    results = []

    for ticker in tickers:
        monthly_df = get_monthly_data(ticker)
        weekly_df = get_weekly_data(ticker)
        daily_df = get_daily_data(ticker)

        if is_weekly_trend_bullish(weekly_df) and is_monthly_trend_bullish(monthly_df):
            if is_daily_entry_signal(daily_df):
                entry_signal = "Entry Confirmed ✅"
                results.append([ticker, entry_signal])
            else:
                entry_signal = "No Entry Yet on Daily Timeframe ⏳"
                #results.append([ticker, entry_signal])
        else:
            entry_signal = "Monthly or Weekly Trend Not Bullish ❌"
            #results.append([ticker, entry_signal])

        #results.append([ticker, entry_signal])
        time.sleep(2)  # Add a delay of 1 second between requests

    # Convert results to DataFrame
    df_results = pd.DataFrame(results, columns=["Asset", "Entry_Signal"])
    return df_results

In [32]:
# Multi-time frame entry Check
#df_results = pd.DataFrame(results).dropna()
etfs_to_check = df_o['Asset'].tolist()
# for quick testing
#etfs_to_check  =['A', 'QQQ','XLV','IBB']
df_signals = check_mtf_entry(etfs_to_check)

df_signals

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

     Asset       Entry_Signal
0      SLV  Entry Confirmed ✅
1     GDXJ  Entry Confirmed ✅
2     RING  Entry Confirmed ✅
3      GDX  Entry Confirmed ✅
4     EUFN  Entry Confirmed ✅
..     ...                ...
60  VAU.AX  Entry Confirmed ✅
61  RIO.AX  Entry Confirmed ✅
62  SFR.AX  Entry Confirmed ✅
63  EVN.AX  Entry Confirmed ✅
64  ORI.AX  Entry Confirmed ✅

[65 rows x 2 columns]

## Generate buy list

In [33]:
df_final = df_signals[df_signals['Entry_Signal'] =="Entry Confirmed ✅"]
final_etfs_to_check = df_final['Asset'].tolist()

#final_etfs_to_check.remove('REMX')
buy_list = check_entry_conditions(final_etfs_to_check)

buy_list

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for SLV is:
False

Macd-V indicator for SLV is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking SLV (1d timeframe)
HA_Open: 59.01, HA_Close: 60.39, HA_Low: 59.01
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for GDXJ is:
True

Macd-V indicator for GDXJ is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking GDXJ (1d timeframe)
HA_Open: 114.35, HA_Close: 116.49, HA_Low: 114.35
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for RING is:
True

Macd-V indicator for RING is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking RING (1d timeframe)
HA_Open: 72.67, HA_Close: 74.00, HA_Low: 72.67
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for GDX is:
True

Macd-V indicator for GDX is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking GDX (1d timeframe)
HA_Open: 85.61, HA_Close: 86.91, HA_Low: 85.56
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for EUFN is:
True

Macd-V indicator for EUFN is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking EUFN (1d timeframe)
HA_Open: 36.31, HA_Close: 36.82, HA_Low: 36.31
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed

Money flow indicator for IAUM is:
True

Macd-V indicator for IAUM is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking IAUM (1d timeframe)
HA_Open: 43.14, HA_Close: 43.22, HA_Low: 43.06
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed

Money flow indicator for GLDM is:
True

Macd-V indicator for GLDM is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking GLDM (1d timeframe)
HA_Open: 85.67, HA_Close: 85.83, HA_Low: 85.51
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for OUNZ is:
True

Macd-V indicator for OUNZ is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking OUNZ (1d timeframe)
HA_Open: 41.65, HA_Close: 41.73, HA_Low: 41.58
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for GLD is:
True

Macd-V indicator for GLD is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking GLD (1d timeframe)
HA_Open: 397.98, HA_Close: 398.69, HA_Low: 397.17
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for IAU is:
True

Macd-V indicator for IAU is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking IAU (1d timeframe)
HA_Open: 81.51, HA_Close: 81.65, HA_Low: 81.34
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for EWP is:
False

Macd-V indicator for EWP is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking EWP (1d timeframe)
HA_Open: 53.08, HA_Close: 53.55, HA_Low: 53.08
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for EWC is:
False

Macd-V indicator for EWC is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking EWC (1d timeframe)
HA_Open: 53.17, HA_Close: 53.60, HA_Low: 53.17
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for IYG is:
True

Macd-V indicator for IYG is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking IYG (1d timeframe)
HA_Open: 91.87, HA_Close: 92.00, HA_Low: 91.72
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for PVAL is:
True

Macd-V indicator for PVAL is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking PVAL (1d timeframe)
HA_Open: 45.38, HA_Close: 45.39, HA_Low: 45.20
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for WTV is:
True

Macd-V indicator for WTV is:
False

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking WTV (1d timeframe)
HA_Open: 94.47, HA_Close: 94.19, HA_Low: 93.97
🔴 Not a bullish candle — no entry confirmation yet.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for MU is:
False

Macd-V indicator for MU is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking MU (1d timeframe)
HA_Open: 244.50, HA_Close: 259.45, HA_Low: 244.50
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for WDC is:
True

Macd-V indicator for WDC is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking WDC (1d timeframe)
HA_Open: 175.36, HA_Close: 179.72, HA_Low: 175.36
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for TER is:
True

Macd-V indicator for TER is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking TER (1d timeframe)
HA_Open: 192.03, HA_Close: 193.78, HA_Low: 191.51
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for LRCX is:
False

Macd-V indicator for LRCX is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking LRCX (1d timeframe)
HA_Open: 163.07, HA_Close: 169.50, HA_Low: 163.07
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for STX is:
True

Macd-V indicator for STX is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking STX (1d timeframe)
HA_Open: 289.44, HA_Close: 298.04, HA_Low: 289.44
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for KLAC is:
True

Macd-V indicator for KLAC is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking KLAC (1d timeframe)
HA_Open: 1217.64, HA_Close: 1247.21, HA_Low: 1217.64
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for CSCO is:
True

Macd-V indicator for CSCO is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking CSCO (1d timeframe)
HA_Open: 77.23, HA_Close: 77.84, HA_Low: 76.79
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for FOXA is:
True

Macd-V indicator for FOXA is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking FOXA (1d timeframe)
HA_Open: 71.16, HA_Close: 71.52, HA_Low: 70.87
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for FOX is:
True

Macd-V indicator for FOX is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking FOX (1d timeframe)
HA_Open: 63.20, HA_Close: 63.52, HA_Low: 63.15
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for TKO is:
True

Macd-V indicator for TKO is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking TKO (1d timeframe)
HA_Open: 211.08, HA_Close: 212.78, HA_Low: 211.06
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for JBHT is:
True

Macd-V indicator for JBHT is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking JBHT (1d timeframe)
HA_Open: 196.26, HA_Close: 196.49, HA_Low: 194.02
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for LUV is:
True

Macd-V indicator for LUV is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking LUV (1d timeframe)
HA_Open: 41.44, HA_Close: 41.05, HA_Low: 40.69
🔴 Not a bullish candle — no entry confirmation yet.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for UAL is:
True

Macd-V indicator for UAL is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking UAL (1d timeframe)
HA_Open: 111.57, HA_Close: 113.31, HA_Low: 111.57
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed

Money flow indicator for DAL is:
True

Macd-V indicator for DAL is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking DAL (1d timeframe)
HA_Open: 70.58, HA_Close: 70.64, HA_Low: 70.02
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for HII is:
True

Macd-V indicator for HII is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking HII (1d timeframe)
HA_Open: 323.85, HA_Close: 330.60, HA_Low: 323.85
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for EXPD is:
True

Macd-V indicator for EXPD is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking EXPD (1d timeframe)
HA_Open: 150.76, HA_Close: 151.53, HA_Low: 149.92
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for CHRW is:
True

Macd-V indicator for CHRW is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking CHRW (1d timeframe)
HA_Open: 160.79, HA_Close: 165.78, HA_Low: 160.79
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for TXT is:
True

Macd-V indicator for TXT is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking TXT (1d timeframe)
HA_Open: 87.40, HA_Close: 88.74, HA_Low: 87.40
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for RTX is:
True

Macd-V indicator for RTX is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking RTX (1d timeframe)
HA_Open: 178.85, HA_Close: 180.72, HA_Low: 178.66
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for PH is:
True

Macd-V indicator for PH is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking PH (1d timeframe)
HA_Open: 873.59, HA_Close: 870.80, HA_Low: 866.42
🔴 Not a bullish candle — no entry confirmation yet.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for AME is:
True

Macd-V indicator for AME is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking AME (1d timeframe)
HA_Open: 201.40, HA_Close: 202.94, HA_Low: 201.40
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for IVZ is:
False

Macd-V indicator for IVZ is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking IVZ (1d timeframe)
HA_Open: 26.53, HA_Close: 26.79, HA_Low: 26.43
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for COF is:
True

Macd-V indicator for COF is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking COF (1d timeframe)
HA_Open: 241.50, HA_Close: 242.79, HA_Low: 240.74
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for SYF is:
True

Macd-V indicator for SYF is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking SYF (1d timeframe)
HA_Open: 83.78, HA_Close: 83.93, HA_Low: 83.00
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for C is:
False

Macd-V indicator for C is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking C (1d timeframe)
HA_Open: 112.35, HA_Close: 114.18, HA_Low: 112.35
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for USB is:
True

Macd-V indicator for USB is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking USB (1d timeframe)
HA_Open: 53.78, HA_Close: 54.01, HA_Low: 53.75
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for CFG is:
False

Macd-V indicator for CFG is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking CFG (1d timeframe)
HA_Open: 58.52, HA_Close: 58.91, HA_Low: 58.49
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for GS is:
True

Macd-V indicator for GS is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking GS (1d timeframe)
HA_Open: 883.09, HA_Close: 889.59, HA_Low: 881.95
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for STT is:
True

Macd-V indicator for STT is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking STT (1d timeframe)
HA_Open: 127.95, HA_Close: 128.04, HA_Low: 127.45
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for WFC is:
False

Macd-V indicator for WFC is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking WFC (1d timeframe)
HA_Open: 92.53, HA_Close: 92.34, HA_Low: 91.60
🔴 Not a bullish candle — no entry confirmation yet.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for TFC is:
True

Macd-V indicator for TFC is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking TFC (1d timeframe)
HA_Open: 49.93, HA_Close: 50.08, HA_Low: 49.84
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for AIZ is:
True

Macd-V indicator for AIZ is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking AIZ (1d timeframe)
HA_Open: 235.40, HA_Close: 238.64, HA_Low: 235.40
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for NTRS is:
True

Macd-V indicator for NTRS is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking NTRS (1d timeframe)
HA_Open: 138.70, HA_Close: 138.94, HA_Low: 138.18
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed

Money flow indicator for MS is:
True

Macd-V indicator for MS is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking MS (1d timeframe)
HA_Open: 176.13, HA_Close: 175.40, HA_Low: 173.46
🔴 Not a bullish candle — no entry confirmation yet.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for AXP is:
False

Macd-V indicator for AXP is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking AXP (1d timeframe)
HA_Open: 378.89, HA_Close: 375.59, HA_Low: 372.77
🔴 Not a bullish candle — no entry confirmation yet.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for EXPE is:
False

Macd-V indicator for EXPE is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking EXPE (1d timeframe)
HA_Open: 284.66, HA_Close: 288.58, HA_Low: 284.66
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for GM is:
False

Macd-V indicator for GM is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking GM (1d timeframe)
HA_Open: 81.06, HA_Close: 81.80, HA_Low: 81.06
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for TPR is:
False

Macd-V indicator for TPR is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking TPR (1d timeframe)
HA_Open: 124.01, HA_Close: 125.25, HA_Low: 124.01
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for TSLA is:
True

Macd-V indicator for TSLA is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking TSLA (1d timeframe)
HA_Open: 478.19, HA_Close: 483.63, HA_Low: 474.72
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for ULTA is:
False

Macd-V indicator for ULTA is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking ULTA (1d timeframe)
HA_Open: 592.18, HA_Close: 599.45, HA_Low: 592.18
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for ROST is:
False

Macd-V indicator for ROST is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking ROST (1d timeframe)
HA_Open: 182.99, HA_Close: 182.45, HA_Low: 181.32
🔴 Not a bullish candle — no entry confirmation yet.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for MAR is:
True

Macd-V indicator for MAR is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking MAR (1d timeframe)
HA_Open: 307.12, HA_Close: 307.66, HA_Low: 304.40
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for IGO.AX is:
False

Macd-V indicator for IGO.AX is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking IGO.AX (1d timeframe)
HA_Open: 7.37, HA_Close: 7.64, HA_Low: 7.37
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for EMR.AX is:
False

Macd-V indicator for EMR.AX is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking EMR.AX (1d timeframe)
HA_Open: 6.15, HA_Close: 6.34, HA_Low: 6.15
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for MIN.AX is:
False

Macd-V indicator for MIN.AX is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking MIN.AX (1d timeframe)
HA_Open: 52.10, HA_Close: 52.50, HA_Low: 51.34
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for VAU.AX is:
True

Macd-V indicator for VAU.AX is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking VAU.AX (1d timeframe)
HA_Open: 5.30, HA_Close: 5.41, HA_Low: 5.24
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for RIO.AX is:
True

Macd-V indicator for RIO.AX is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking RIO.AX (1d timeframe)
HA_Open: 141.99, HA_Close: 142.53, HA_Low: 141.10
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Money flow indicator for SFR.AX is:
True

Macd-V indicator for SFR.AX is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking SFR.AX (1d timeframe)
HA_Open: 16.83, HA_Close: 17.03, HA_Low: 16.83
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

[*********************100%***********************]  1 of 1 completed

Money flow indicator for EVN.AX is:
True

Macd-V indicator for EVN.AX is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking EVN.AX (1d timeframe)
HA_Open: 12.46, HA_Close: 12.64, HA_Low: 12.34
🟢 Candle is green but not flat-bottomed — still bullish, but less strong.

[*********************100%***********************]  1 of 1 completed

Money flow indicator for ORI.AX is:
False

Macd-V indicator for ORI.AX is:
True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

🔍 Checking ORI.AX (1d timeframe)
HA_Open: 24.38, HA_Close: 24.70, HA_Low: 24.38
✅ Heikin Ashi candle is GREEN with a FLAT bottom — strong bullish signal!

     Asset             Entry_Signal
0      SLV  Extended Momentum Entry
1     GDXJ              Aline Entry
2     RING              Aline Entry
3      GDX              Aline Entry
4     EUFN  Extended Momentum Entry
..     ...                      ...
60  VAU.AX              Aline Entry
61  RIO.AX              Aline Entry
62  SFR.AX              Aline Entry
63  EVN.AX              Aline Entry
64  ORI.AX  Extended Momentum Entry

[65 rows x 2 columns]

# Find and filter correlated assets to reduce concentration risk.

In [34]:

def get_uncorrelated_picks(tickers, ranked_picks, threshold=0.66, period="3mo", interval="1d"):
    """
    Filters a ranked list of tickers to return only uncorrelated picks.

    Parameters:
    -----------
    tickers : list
        All candidate tickers.
    ranked_picks : list
        Ranked list of tickers (best to worst).
    threshold : float
        Correlation threshold (default 0.66).
    period : str
        Data period for yfinance (default "3mo").
    interval : str
        Data interval (default "1d").

    Returns:
    --------
    final_selection : list
        List of uncorrelated tickers.
    corr_matrix : DataFrame
        Correlation matrix of daily returns.
    """
    # Step 1: Get prices
    data = yf.download(tickers, period=period, interval=interval,auto_adjust=True)["Close"]
    data = data.ffill()

    # Step 2: Convert to daily returns
    returns = data.pct_change().dropna()

    # Step 3: Correlation matrix
    corr_matrix = returns.corr()

    # Step 4: Filter uncorrelated picks
    final_selection = []
    for pick in ranked_picks:
        if all(abs(corr_matrix.loc[pick, sel]) <= threshold for sel in final_selection):
            final_selection.append(pick)

    return final_selection, corr_matrix

In [35]:
# Apply TA filters and prioritize ETFs
results = []
buy_list = buy_list[buy_list['Entry_Signal'].isin([
    'Aline Entry',
    'Extended Momentum Entry'
])]


for etf in buy_list['Asset'].to_list():
   df          = get_daily_data(etf)
   price       = df['Close'].iloc[-1]
   above_21EMA = price > df['21_day_EMA'].iloc[-1]
   above_50sma = price  > df['50_day_SMA'].iloc[-1]

   sma_slope_50 = df['SMA_Slope_50'].iloc[-1]> 0
   vwap_df     = anchored_vwap(etf, lookback_weeks=2)
   vwap_sy     = anchored_vwap_old(etf, start_of_year)
   ytd_vwap    = vwap_sy['anchored_vwap'].iloc[-1]
   # MTD
   vwap_mtd     = anchored_vwap_old(etf, first_day_month)
   mtd_vwap    = vwap_mtd['anchored_vwap'].iloc[-1]
   # WTD
   vwap_wtd     = anchored_vwap_old(etf, first_day_week )
   wtd_vwap    = vwap_wtd['anchored_vwap'].iloc[-1]

   print("Year to date VWAP is :", ytd_vwap)
   vwap        = vwap_df['Anchored_VWAP'].iloc[-1]
   vwap_signal = vwap_df['Signal'].iloc[-1]

   swing_high =  vwap_df['Swing_High_Price'].iloc[-1]
   above_vwap  = price > vwap
   above_ytd_vwap = price > ytd_vwap


   if  above_50sma and above_ytd_vwap and sma_slope_50 and vwap_signal and wtd_vwap :
    support_level, latest_price, trail,resistance = calculate_risk_reward(df)
    entry_price = latest_price + min(0.25, 0.1*trail)
    trail = 1* trail
    risk = np.abs(entry_price- support_level)
    take_profit_1=  entry_price+ (1 *risk)
    resistance_level = entry_price + (1.5 *risk)
    reward = resistance_level - entry_price
    risk_reward_ratio = reward / risk
    # Ensure risk is greater than zero before division
    if risk > 0:
        rr_ratio_1  = np.abs(take_profit_1- entry_price) / risk
        rr_ratio  = reward / risk
    else:
        rr_ratio = np.nan

    take_profit1_perc = ((take_profit_1- entry_price )/entry_price )*100
    stop_loss_perc = ((support_level- entry_price)/entry_price )*100
    take_profit_perc = ((resistance_level- entry_price )/entry_price )*100
    # Fetch the Entry_Signal from buy_list
    entry_signal = buy_list.loc[buy_list['Asset'] == etf, 'Entry_Signal'].values[0]

    # Append results with Entry_Signal
    results.append({
            "Asset": etf,
            "Swing High": swing_high,
            "Risk-Reward_1": rr_ratio_1,
            "Risk-Reward": rr_ratio,
            "Stop Out Price": support_level,
            "Take Profit1": take_profit_1,
            "Target Price": resistance_level,
            "Current Price": latest_price,
            "Entry Price": entry_price,
            "Trail Price": trail,
            "Entry Signal": entry_signal,  # Add entry signal
            "stop_loss_perc": stop_loss_perc,
            "take_profit1_perc": take_profit1_perc,
            "take_profit_perc": take_profit_perc
            #"Anchored VWAP": vwap,
            #"MTD VWAP": mtd_vwap,
            #"WTD VWAP": wtd_vwap,
            #"YTD VWAP": ytd_vwap
        })

    time.sleep(2)  # Add a delay of 1 second between requests


# Sort ETFs by highest risk-to-reward ratio
try:
   df_results = pd.DataFrame(results).dropna().sort_values(by="Risk-Reward", ascending=False).reset_index(drop = True)
except Exception as e:
  print("No Asset to buy today, check back some other time!")
  df_results = pd.DataFrame({"Asset": ["No Asset available"]})

df2 = df_results.merge(df_o[['Asset','Type', 'score']], on='Asset', how='left')
df2['timestamp'] = datetime.now()
df2 = df2.sort_values(by='score', ascending=False)
df2.head()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for SLV starting from 2025-12-19 (recent high = 61.16)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 38.35295728628131

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for GDXJ starting from 2025-12-19 (recent high = 118.87)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 74.6495004307813

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for RING starting from 2025-12-19 (recent high = 75.43)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 51.946634935549326

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for GDX starting from 2025-12-19 (recent high = 88.69)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 58.2293764119172

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for EUFN starting from 2025-12-19 (recent high = 36.92)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 29.868882349046995

[*********************100%***********************]  1 of 1 completed

Anchored VWAP for IAUM starting from 2025-12-18 (recent high = 43.60)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 35.22622569174506

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for GLDM starting from 2025-12-18 (recent high = 86.57)

[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 70.58933799930021

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for OUNZ starting from 2025-12-18 (recent high = 42.10)

[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 33.25329136087338

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for GLD starting from 2025-12-18 (recent high = 402.21)

[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 324.4356795278629

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for IAU starting from 2025-12-18 (recent high = 82.38)

[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 66.11093771478532

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for EWP starting from 2025-12-19 (recent high = 53.66)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 43.5252150475112

[*********************100%***********************]  1 of 1 completed

Anchored VWAP for EWC starting from 2025-12-19 (recent high = 53.92)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 44.22406548169684

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for IYG starting from 2025-12-12 (recent high = 92.80)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 82.32979602978972

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for PVAL starting from 2025-12-12 (recent high = 45.86)

[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 40.459349506527516

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for MU starting from 2025-12-19 (recent high = 268.38)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 136.8972480781499

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for WDC starting from 2025-12-11 (recent high = 188.77)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 82.8197372793877

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for TER starting from 2025-12-08 (recent high = 205.00)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 115.34385284928953

[*********************100%***********************]  1 of 1 completed

Anchored VWAP for LRCX starting from 2025-12-19 (recent high = 173.58)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 101.802632693252

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for STX starting from 2025-12-11 (recent high = 308.93)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 159.11837790999607

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for KLAC starting from 2025-12-19 (recent high = 1263.57)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 869.6735287299045

[*********************100%***********************]  1 of 1 completed

Anchored VWAP for CSCO starting from 2025-12-10 (recent high = 80.82)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 65.53703239268675

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for FOXA starting from 2025-12-15 (recent high = 72.96)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 56.552310577395374

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for FOX starting from 2025-12-11 (recent high = 64.22)

[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 52.50257894335555

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for TKO starting from 2025-12-17 (recent high = 216.14)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 169.44723908594025

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for JBHT starting from 2025-12-11 (recent high = 204.43)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 152.21818615639512

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for UAL starting from 2025-12-17 (recent high = 114.83)

[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 88.03918154522403

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for DAL starting from 2025-12-16 (recent high = 72.34)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 53.960232378578254

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for HII starting from 2025-12-19 (recent high = 337.44)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 232.77380044017264

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for EXPD starting from 2025-12-15 (recent high = 155.04)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 119.34975159002516

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for CHRW starting from 2025-12-19 (recent high = 167.10)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 115.39914599802948

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for TXT starting from 2025-12-19 (recent high = 89.92)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 77.67383062375959

[*********************100%***********************]  1 of 1 completed

Anchored VWAP for RTX starting from 2025-12-19 (recent high = 183.24)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 144.14047704345535

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for AME starting from 2025-12-12 (recent high = 204.43)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 181.64199054592117

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for IVZ starting from 2025-12-11 (recent high = 27.31)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 18.53183229096553

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for COF starting from 2025-12-17 (recent high = 244.82)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 198.68076432763405

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for SYF starting from 2025-12-11 (recent high = 86.22)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 64.13719062599962

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for C starting from 2025-12-19 (recent high = 115.61)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 83.5976466958918

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for USB starting from 2025-12-18 (recent high = 54.41)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 44.8613187913418

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for CFG starting from 2025-12-19 (recent high = 59.33)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 45.56707822199504

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for GS starting from 2025-12-11 (recent high = 919.10)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 655.8263535761224

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for STT starting from 2025-12-12 (recent high = 131.36)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 102.26055109835826

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for WFC starting from 2025-12-15 (recent high = 94.26)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 76.8859776878936

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for TFC starting from 2025-12-18 (recent high = 50.50)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 42.00967496106934

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for AIZ starting from 2025-12-18 (recent high = 240.58)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 203.73430357845612

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for NTRS starting from 2025-12-12 (recent high = 140.75)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 114.00711663604768

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for MS starting from 2025-12-11 (recent high = 181.98)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 136.1720537020176

[*********************100%***********************]  1 of 1 completed

Anchored VWAP for EXPE starting from 2025-12-19 (recent high = 292.42)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 195.02290740259696

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for GM starting from 2025-12-16 (recent high = 83.04)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 53.910487661497896

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for TPR starting from 2025-12-18 (recent high = 127.54)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 87.19774636629094

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for TSLA starting from 2025-12-17 (recent high = 495.28)

[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 343.03293415226204

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for ULTA starting from 2025-12-05 (recent high = 611.90)

[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 450.1156204317897

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for MAR starting from 2025-12-18 (recent high = 311.69)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 264.3376413304483

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for IGO.AX starting from 2025-12-19 (recent high = 7.82)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 4.841076679502978

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for EMR.AX starting from 2025-12-18 (recent high = 6.44)

[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 4.321919185678022

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for MIN.AX starting from 2025-12-15 (recent high = 53.38)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 30.033610929969733

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for VAU.AX starting from 2025-12-19 (recent high = 5.51)

[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 3.4115718672372064

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for RIO.AX starting from 2025-12-18 (recent high = 143.89)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 116.22730190824242

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for SFR.AX starting from 2025-12-19 (recent high = 17.25)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 12.075678101665476

[*********************100%***********************]  1 of 1 completed

Anchored VWAP for EVN.AX starting from 2025-12-12 (recent high = 12.81)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 8.377390635455352

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Anchored VWAP for ORI.AX starting from 2025-12-19 (recent high = 24.97)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Year to date VWAP is : 18.96202524293443

,Asset,Swing High,Risk-Reward_1,Risk-Reward,Stop Out Price,Take Profit1,Target Price,Current Price,Entry Price,Trail Price,Entry Signal,stop_loss_perc,take_profit1_perc,take_profit_perc,Type,score,timestamp
41,SLV,61.160000,1.0,1.5,56.183644,66.078957,68.552785,60.930000,61.131300,2.013000,Extended Momentum Entry,-8.093491,8.093491,12.140236,ETF,3.49,2025-12-21 17:53:52.465950
36,MU,268.380005,1.0,1.5,229.453279,302.886748,321.245115,265.920013,266.170013,16.680994,Extended Momentum Entry,-13.794467,13.794467,20.691700,Stock,2.89,2025-12-21 17:53:52.465950
37,IGO.AX,7.820000,1.0,1.5,6.968300,8.458300,8.830800,7.680000,7.713300,0.333000,Extended Momentum Entry,-9.658646,9.658646,14.487969,ASX,2.66,2025-12-21 17:53:52.465950
38,WDC,188.770004,1.0,1.5,162.903593,199.756411,208.969615,181.080002,181.330002,11.478001,Aline Entry,-10.161809,10.161809,15.242714,Stock,2.55,2025-12-21 17:53:52.465950
25,EXPE,292.420013,1.0,1.5,272.534387,306.465613,314.948420,289.250000,289.500000,8.500000,Aline Entry,-5.860315,5.860315,8.790473,Stock,2.09,2025-12-21 17:53:52.465950

## Sentiment Score

In [36]:
NEWS_API_KEY = "15c99612003d4971ad86698b50ed0bd7"  # Get one free from https://newsapi.org/
LOOKBACK_DAYS = 3

# Fetch recent news
def fetch_news(ticker, lookback_days=3):
    url = f"https://newsapi.org/v2/everything?q={ticker}&language=en&from={(datetime.now() - timedelta(days=lookback_days)).date()}&apiKey={NEWS_API_KEY}"
    resp = requests.get(url).json()
    if "articles" not in resp:
        return []
    return [a["title"] for a in resp["articles"]]

# Finbert Sentiment Scoring
finbert = pipeline("sentiment-analysis", model="ProsusAI/finbert")

def get_sentiment_scores(news_list):
    if not news_list:
        return 0
    results = finbert(news_list)
    time.sleep(2)  # Add a delay of 1 second between requests
    scores = [1 if r["label"] == "positive" else -1 if r["label"] == "negative" else 0 for r in results]
    return np.mean(scores)

def build_sentiment_table(TICKERS):
    records = []
    for ticker in TICKERS:
        print(f"Processing {ticker}...")
        news = fetch_news(ticker, LOOKBACK_DAYS)
        sentiment_score = get_sentiment_scores(news)
        combined = {
            "Ticker": ticker,
            "Sentiment": sentiment_score
        }
        records.append(combined)
    df = pd.DataFrame(records)

    # Weighted score (adjustable)
    df["Composite_Score"] = (

        df["Sentiment"].rank(pct=True)
    )

    df = df.sort_values("Composite_Score", ascending=False).reset_index(drop=True)
    return df

# Run sentiment scoring
tickers = df2['Asset'].tolist()
results = build_sentiment_table(tickers)
top_assets = results[results["Sentiment"] >= 0]

top_assets.head()

Device set to use cpu

Processing SLV...
Processing MU...
Processing IGO.AX...
Processing WDC...
Processing EXPE...
Processing EMR.AX...
Processing GM...
Processing MIN.AX...
Processing LRCX...
Processing UAL...
Processing DAL...
Processing TPR...
Processing GDXJ...
Processing STX...
Processing IVZ...
Processing VAU.AX...
Processing SYF...
Processing COF...
Processing TSLA...
Processing C...
Processing FOXA...
Processing USB...
Processing RIO.AX...
Processing FOX...
Processing ULTA...
Processing RING...
Processing HII...
Processing GDX...
Processing CFG...
Processing EXPD...
Processing CHRW...
Processing GS...
Processing STT...
Processing TKO...
Processing WFC...
Processing EVN.AX...
Processing ORI.AX...
Processing TFC...
Processing TXT...
Processing MAR...
Processing AIZ...
Processing NTRS...
Processing GLDM...
Processing IAUM...
Processing OUNZ...
Processing IAU...
Processing GLD...
Processing RTX...
Processing CSCO...
Processing AME...
Processing EWC...
Processing IYG...
Processing PVAL...

  Ticker  Sentiment  Composite_Score
0    GLD   1.000000         1.000000
1   LRCX   0.666667         0.981132
2    TPR   0.500000         0.943396
3    GDX   0.500000         0.943396
4   EXPE   0.500000         0.943396

# ETF Entries (Day Trade Extended Momentum Entry	)

In [37]:
# Fetch the Entry_Signal from buy_list
try:
  df3 = df2[df2['Asset'].isin(top_assets['Ticker'])]
  #df3 = df2.copy()
  etf_buy= df3[(df3['Type'] == 'ETF') & (df3['Entry Signal'] == 'Extended Momentum Entry')].reset_index(drop=True)
  tickers = etf_buy['Asset'].tolist()  # Replace with your list of tickers
  ranked_picks = tickers

  final_etf_selection, corr_matrix = get_uncorrelated_picks(tickers, ranked_picks, threshold=0.66)
  #print("Final uncorrelated picks:", final_selection)
  print("\nCorrelation matrix:\n", corr_matrix)

  # Keep only rows where Asset is in filtered
  filtered_etf_list = etf_buy[etf_buy["Asset"].isin(final_etf_selection)]

except Exception as e:
  print("No Asset to buy today, check back some other time!")
  filtered_etf_list = pd.DataFrame({"Asset": ["No Asset available"]})

filtered_etf_list

[*********************100%***********************]  1 of 1 completed

Correlation matrix:
 Ticker  SLV
Ticker
SLV     1.0

,Asset,Swing High,Risk-Reward_1,Risk-Reward,Stop Out Price,Take Profit1,Target Price,Current Price,Entry Price,Trail Price,Entry Signal,stop_loss_perc,take_profit1_perc,take_profit_perc,Type,score,timestamp
0,SLV,61.16,1.0,1.5,56.183644,66.078957,68.552785,60.93,61.1313,2.013,Extended Momentum Entry,-8.093491,8.093491,12.140236,ETF,3.49,2025-12-21 17:53:52.465950

 # ETF Entries (Aline Entry	)

In [38]:
# Fetch the Entry_Signal from buy_list
try:
  df3 = df2[df2['Asset'].isin(top_assets['Ticker'])]
  etf_buy= df3[(df3['Type'] == 'ETF') & (df3['Entry Signal'] == 'Aline Entry')].reset_index(drop=True)
  tickers = etf_buy['Asset'].tolist()  # Replace with your list of tickers
  ranked_picks = tickers
  final_etf_selection, corr_matrix = get_uncorrelated_picks(tickers, ranked_picks, threshold=0.66)

  #print("Final uncorrelated picks:", final_selection)
  print("\nCorrelation matrix:\n", corr_matrix)

  # Keep only rows where Asset is in filtered
  filtered_etf_list2 = etf_buy[etf_buy["Asset"].isin(final_etf_selection)]

except Exception as e:
  print("No Asset to buy today, check back some other time!")
  filtered_etf_list2 = pd.DataFrame({"Asset": ["No Asset available"]})

filtered_etf_list2

[*********************100%***********************]  10 of 10 completed

Correlation matrix:
 Ticker       EWC       GDX      GDXJ       GLD      GLDM       IAU      IAUM  \
Ticker
EWC     1.000000  0.668256  0.673460  0.473506  0.470045  0.469623  0.469859
GDX     0.668256  1.000000  0.989495  0.824832  0.822258  0.821906  0.821610
GDXJ    0.673460  0.989495  1.000000  0.826957  0.824323  0.823915  0.823753
GLD     0.473506  0.824832  0.826957  1.000000  0.999643  0.999659  0.999517
GLDM    0.470045  0.822258  0.824323  0.999643  1.000000  0.999902  0.999797
IAU     0.469623  0.821906  0.823915  0.999659  0.999902  1.000000  0.999858
IAUM    0.469859  0.821610  0.823753  0.999517  0.999797  0.999858  1.000000
IYG     0.638309  0.213820  0.231618  0.169471  0.171737  0.172174  0.172194
OUNZ    0.469815  0.823813  0.826192  0.999483  0.999797  0.999786  0.999715
PVAL    0.701803  0.291078  0.296717  0.170697  0.172282  0.173033  0.171325

Ticker       IYG      OUNZ      PVAL
Ticker
EWC     0.638309  0.469815  0.701803
GDX     0.213820  0.823813  0.291078
GDXJ    0.231618  0.826192  0.296717
GLD     0.169471  0.999483  0.170697
GLDM    0.171737  0.999797  0.172282
IAU     0.172174  0.999786  0.173033
IAUM    0.172194  0.999715  0.171325
IYG     1.000000  0.171825  0.844989
OUNZ    0.171825  1.000000  0.173502
PVAL    0.844989  0.173502  1.000000

,Asset,Swing High,Risk-Reward_1,Risk-Reward,Stop Out Price,Take Profit1,Target Price,Current Price,Entry Price,Trail Price,Entry Signal,stop_loss_perc,take_profit1_perc,take_profit_perc,Type,score,timestamp
0,GDXJ,118.870003,1.0,1.5,109.199315,126.560679,130.901020,117.629997,117.879997,4.406000,Aline Entry,-7.363999,7.363999,11.045998,ETF,1.45,2025-12-21 17:53:52.465950
8,IYG,92.796325,1.0,1.5,90.414674,94.063720,94.975981,92.129997,92.239197,1.091993,Aline Entry,-1.978034,1.978034,2.967052,ETF,0.35,2025-12-21 17:53:52.465950

# US Stock Entries (Day Trade)

In [39]:
# SP 500 stocks
# Fetch the Entry_Signal from buy_list
try:
  sp500_stocks_dt = df3[(df3['Type'] == 'Stock') & (df3['Entry Signal'] == 'Extended Momentum Entry')].reset_index(drop=True)
except Exception as e:
  print("No Asset to buy today, check back some other time!")
  sp500_stocks_dt = pd.DataFrame({"Asset": ["No Asset available"]})

sp500_stocks_dt

,Asset,Swing High,Risk-Reward_1,Risk-Reward,Stop Out Price,Take Profit1,Target Price,Current Price,Entry Price,Trail Price,Entry Signal,stop_loss_perc,take_profit1_perc,take_profit_perc,Type,score,timestamp
0,MU,268.380005,1.0,1.5,229.453279,302.886748,321.245115,265.920013,266.170013,16.680994,Extended Momentum Entry,-13.794467,13.794467,20.691700,Stock,2.89,2025-12-21 17:53:52.465950
1,C,115.610001,1.0,1.5,109.601514,120.583687,123.329230,114.860001,115.092600,2.325999,Extended Momentum Entry,-4.771016,4.771016,7.156524,Stock,1.28,2025-12-21 17:53:52.465950
2,HII,337.440002,1.0,1.5,316.140988,357.639041,368.013554,336.640015,336.890015,9.417996,Extended Momentum Entry,-6.158991,6.158991,9.238487,Stock,1.10,2025-12-21 17:53:52.465950
3,CHRW,167.100006,1.0,1.5,157.001396,176.418617,181.272922,166.460007,166.710007,4.161003,Extended Momentum Entry,-5.823652,5.823652,8.735478,Stock,1.05,2025-12-21 17:53:52.465950
4,TXT,89.919998,1.0,1.5,85.386747,93.898618,96.026586,89.459999,89.642682,1.826833,Extended Momentum Entry,-4.747666,4.747666,7.121499,Stock,0.83,2025-12-21 17:53:52.465950
5,AIZ,240.580002,1.0,1.5,229.335686,249.204323,254.171482,239.020004,239.270004,4.301999,Extended Momentum Entry,-4.151928,4.151928,6.227892,Stock,0.67,2025-12-21 17:53:52.465950

# US Stock Entries (Aline Entry)

In [40]:
# Fetch the Entry_Signal from buy_list
# Filter US stocks for Aline Entry
try:
  us_stocks = df3[(df3['Type'] == 'Stock') & (df3['Entry Signal'] == 'Aline Entry')].reset_index(drop=True)

  tickers = us_stocks['Asset'].tolist()  # Replace with your list of tickers
  ranked_picks = tickers

  final_stock_selection, corr_matrix = get_uncorrelated_picks(tickers, ranked_picks, threshold=0.66)

  #print("Final uncorrelated picks:", final_selection)
  print("\nCorrelation matrix:\n", corr_matrix)

  # Keep only rows where Asset is in filtered
  filtered_stock_list = us_stocks [us_stocks ["Asset"].isin(final_stock_selection)]
except Exception as e:
  print("No Asset to buy today, check back some other time!")
  filtered_stock_list = pd.DataFrame({"Asset": ["No Asset available"]})

filtered_stock_list

[*********************100%***********************]  17 of 17 completed

Correlation matrix:
 Ticker       AME       CFG       COF      CSCO      EXPD      EXPE      FOXA  \
Ticker
AME     1.000000  0.373017  0.343338  0.269109  0.309006  0.224413  0.550943
CFG     0.373017  1.000000  0.800284  0.218912  0.269426  0.501883  0.333141
COF     0.343338  0.800284  1.000000  0.185400  0.211511  0.469387  0.252006
CSCO    0.269109  0.218912  0.185400  1.000000 -0.014895  0.143899  0.078071
EXPD    0.309006  0.269426  0.211511 -0.014895  1.000000  0.174825  0.350770
EXPE    0.224413  0.501883  0.469387  0.143899  0.174825  1.000000  0.190516
FOXA    0.550943  0.333141  0.252006  0.078071  0.350770  0.190516  1.000000
GS      0.295356  0.457554  0.430752  0.146052  0.191155  0.301255  0.339014
LRCX    0.314933  0.341542  0.332581  0.381795  0.117104  0.197778  0.114963
NTRS    0.379646  0.744869  0.614127  0.147992  0.239439  0.450499  0.362996
RTX     0.237233  0.197596  0.159545  0.120405  0.130099  0.197764  0.199696
STX     0.147882  0.063523  0.066238  0.015976 -0.044422  0.051775  0.061319
SYF     0.444169  0.806845  0.812523  0.232591  0.286275  0.461700  0.347112
TPR     0.213386  0.358579  0.313994  0.093863  0.370441  0.312267  0.179746
TSLA    0.141000  0.202952  0.282730  0.110139  0.005468  0.025675 -0.149232
WDC     0.145999  0.030196  0.057065  0.084525  0.042182  0.008746 -0.042176
WFC     0.360305  0.643062  0.542318  0.214374  0.251798  0.273371  0.166702

Ticker        GS      LRCX      NTRS       RTX       STX       SYF       TPR  \
Ticker
AME     0.295356  0.314933  0.379646  0.237233  0.147882  0.444169  0.213386
CFG     0.457554  0.341542  0.744869  0.197596  0.063523  0.806845  0.358579
COF     0.430752  0.332581  0.614127  0.159545  0.066238  0.812523  0.313994
CSCO    0.146052  0.381795  0.147992  0.120405  0.015976  0.232591  0.093863
EXPD    0.191155  0.117104  0.239439  0.130099 -0.044422  0.286275  0.370441
EXPE    0.301255  0.197778  0.450499  0.197764  0.051775  0.461700  0.312267
FOXA    0.339014  0.114963  0.362996  0.199696  0.061319  0.347112  0.179746
GS      1.000000  0.472294  0.608759  0.168304  0.227981  0.501985  0.282387
LRCX    0.472294  1.000000  0.333550  0.182039  0.670205  0.342449  0.404880
NTRS    0.608759  0.333550  1.000000  0.205783  0.045752  0.671746  0.338029
RTX     0.168304  0.182039  0.205783  1.000000  0.083266  0.180295  0.157261
STX     0.227981  0.670205  0.045752  0.083266  1.000000  0.038162  0.238915
SYF     0.501985  0.342449  0.671746  0.180295  0.038162  1.000000  0.369608
TPR     0.282387  0.404880  0.338029  0.157261  0.238915  0.369608  1.000000
TSLA    0.195263  0.520601  0.171497  0.251020  0.312107  0.204303  0.296621
WDC     0.183511  0.599127  0.054997  0.102266  0.849378  0.035924  0.185505
WFC     0.435498  0.194921  0.687688  0.113198 -0.103024  0.578794  0.249643

Ticker      TSLA       WDC       WFC
Ticker
AME     0.141000  0.145999  0.360305
CFG     0.202952  0.030196  0.643062
COF     0.282730  0.057065  0.542318
CSCO    0.110139  0.084525  0.214374
EXPD    0.005468  0.042182  0.251798
EXPE    0.025675  0.008746  0.273371
FOXA   -0.149232 -0.042176  0.166702
GS      0.195263  0.183511  0.435498
LRCX    0.520601  0.599127  0.194921
NTRS    0.171497  0.054997  0.687688
RTX     0.251020  0.102266  0.113198
STX     0.312107  0.849378 -0.103024
SYF     0.204303  0.035924  0.578794
TPR     0.296621  0.185505  0.249643
TSLA    1.000000  0.403654  0.154877
WDC     0.403654  1.000000 -0.070071
WFC     0.154877 -0.070071  1.000000

,Asset,Swing High,Risk-Reward_1,Risk-Reward,Stop Out Price,Take Profit1,Target Price,Current Price,Entry Price,Trail Price,Entry Signal,stop_loss_perc,take_profit1_perc,take_profit_perc,Type,score,timestamp
0,WDC,188.770004,1.0,1.5,162.903593,199.756411,208.969615,181.080002,181.330002,11.478001,Aline Entry,-10.161809,10.161809,15.242714,Stock,2.55,2025-12-21 17:53:52.465950
1,EXPE,292.420013,1.0,1.5,272.534387,306.465613,314.948420,289.250000,289.500000,8.500000,Aline Entry,-5.860315,5.860315,8.790473,Stock,2.09,2025-12-21 17:53:52.465950
2,LRCX,173.580002,1.0,1.5,156.048671,188.991338,197.227004,172.270004,172.520004,8.199001,Aline Entry,-9.547492,9.547492,14.321238,Stock,1.74,2025-12-21 17:53:52.465950
3,TPR,127.540001,1.0,1.5,118.932097,132.407899,135.776850,125.419998,125.669998,3.592001,Aline Entry,-5.361583,5.361583,8.042375,Stock,1.59,2025-12-21 17:53:52.465950
5,SYF,86.220001,1.0,1.5,81.334432,88.427129,90.200303,84.680000,84.880780,2.007800,Aline Entry,-4.178035,4.178035,6.267052,Stock,1.32,2025-12-21 17:53:52.465950
7,TSLA,495.279999,1.0,1.5,450.497514,512.402510,527.878760,481.200012,481.450012,19.910001,Aline Entry,-6.429016,6.429016,9.643524,Stock,1.28,2025-12-21 17:53:52.465950
8,FOXA,72.959999,1.0,1.5,69.388597,74.444697,75.708722,71.769997,71.916647,1.466501,Aline Entry,-3.515250,3.515250,5.272875,Stock,1.21,2025-12-21 17:53:52.465950
10,EXPD,155.039993,1.0,1.5,147.570605,158.669385,161.444080,152.869995,153.119995,3.287999,Aline Entry,-3.624210,3.624210,5.436315,Stock,1.06,2025-12-21 17:53:52.465950
11,GS,919.099976,1.0,1.5,856.314939,931.145021,949.852542,893.479980,893.729980,23.230981,Aline Entry,-4.186392,4.186392,6.279588,Stock,1.05,2025-12-21 17:53:52.465950
12,WFC,94.260002,1.0,1.5,89.905667,96.502737,98.152005,93.010002,93.204202,1.941998,Aline Entry,-3.539041,3.539041,5.308562,Stock,0.97,2025-12-21 17:53:52.465950
14,RTX,183.240005,1.0,1.5,174.331365,190.188624,194.152939,182.009995,182.259995,4.024002,Aline Entry,-4.350175,4.350175,6.525263,Stock,0.59,2025-12-21 17:53:52.465950
15,CSCO,80.820000,1.0,1.5,76.044269,81.136727,82.409842,78.419998,78.590498,1.704998,Aline Entry,-3.239869,3.239869,4.859804,Stock,0.54,2025-12-21 17:53:52.465950
16,AME,204.429993,1.0,1.5,198.192795,208.887192,211.560791,203.289993,203.539993,3.297000,Aline Entry,-2.627100,2.627100,3.940650,Stock,0.45,2025-12-21 17:53:52.465950

# ASX Stock Entries (Aline Entry)

In [41]:
# Fetch the Entry_Signal from buy_list
try:
  df3 = df2[df2['Asset'].isin(top_assets['Ticker'])]
  asx_buy= df3[(df3['Type'] == 'ASX') & (df3['Entry Signal'] == 'Aline Entry')].reset_index(drop=True)
  tickers = asx_buy['Asset'].tolist()  # Replace with your list of tickers
  ranked_picks = tickers
  final_asx_selection, corr_matrix = get_uncorrelated_picks(tickers, ranked_picks, threshold=0.66)

  #print("Final uncorrelated picks:", final_selection)
  print("\nCorrelation matrix:\n", corr_matrix)

  # Keep only rows where Asset is in filtered
  filtered_asx_list2 = asx_buy[asx_buy["Asset"].isin(final_asx_selection)]

except Exception as e:
  print("No Asset to buy today, check back some other time!")
  filtered_asx_list2 = pd.DataFrame({"Asset": ["No Asset available"]})

filtered_asx_list2

[*********************100%***********************]  4 of 4 completed

Correlation matrix:
 Ticker    EVN.AX    MIN.AX    RIO.AX    VAU.AX
Ticker
EVN.AX  1.000000  0.364890  0.411249  0.730982
MIN.AX  0.364890  1.000000  0.274426  0.233992
RIO.AX  0.411249  0.274426  1.000000  0.335815
VAU.AX  0.730982  0.233992  0.335815  1.000000

,Asset,Swing High,Risk-Reward_1,Risk-Reward,Stop Out Price,Take Profit1,Target Price,Current Price,Entry Price,Trail Price,Entry Signal,stop_loss_perc,take_profit1_perc,take_profit_perc,Type,score,timestamp
0,MIN.AX,53.380001,1.0,1.5,49.830157,55.855846,57.362269,52.650002,52.843001,1.930000,Aline Entry,-5.701502,5.701502,8.552253,ASX,1.75,2025-12-21 17:53:52.465950
1,VAU.AX,5.510000,1.0,1.5,5.047975,5.772524,5.953662,5.390000,5.410250,0.202500,Aline Entry,-6.696079,6.696079,10.044119,ASX,1.34,2025-12-21 17:53:52.465950
2,RIO.AX,143.889999,1.0,1.5,138.276605,148.363409,150.885110,143.070007,143.320007,2.730501,Aline Entry,-3.518980,3.518980,5.278470,ASX,1.15,2025-12-21 17:53:52.465950